// packages/lit/src/components/radio-group/radio-group.ts
import { LitElement, css, html, nothing } from 'lit'
import { Circle } from 'lucide'
import { cn } from '../../lib/utils'
import { tailwind } from '../../lib/styles'
import { ThemeController } from '../../lib/theme'
import { icon } from '../../lib/icon'

export type RadioOption = string | { label: string; value: string; disabled?: boolean }

interface Opt {
  value: string
  label: string
  disabled: boolean
}

type ButtonSize = 'small' | 'middle' | 'large'

// --- class tables: React's radio-group.tsx verbatim ---------------------------
const groupDensityClasses = {
  compact: 'gap-1',
  default: 'gap-3',
  comfortable: 'gap-4',
}

const itemDensityClasses = {
  compact: 'gap-1',
  default: 'gap-2',
  comfortable: 'gap-3',
}

const buttonSizeClasses = {
  small: 'h-7 px-2.5 text-xs',
  middle: 'h-8 px-4 text-sm',
  large: 'h-10 px-4.5 text-base',
}

const buttonVariantClasses = {
  outline: cn(
    'border border-input bg-transparent text-foreground hover:text-foreground hover:bg-muted/50',
    'data-[state=checked]:border-primary data-[state=checked]:text-primary',
    'disabled:hover:bg-transparent',
  ),
  solid: cn(
    'border border-input bg-transparent text-foreground hover:text-foreground hover:bg-muted/50',
    'data-[state=checked]:border-primary data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground',
    'disabled:hover:bg-transparent',
  ),
}

// RadioGroupItem defaults (size="md", color="primary").
const itemClasses = cn(
  'border-input text-primary focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:bg-input/30 aspect-square shrink-0 rounded-full border shadow-sm transition-colors duration-200 outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50',
  'size-4',
  'data-[state=checked]:border-primary',
)
const indicatorIconClasses = cn(
  'absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 fill-current text-current',
  'size-2',
)
// <Label> (registry label.tsx) — the Default story pairs each item with one.
const labelComponentClasses =
  'flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50'

function normalizeOption(option: RadioOption): Opt {
  if (typeof option === 'string') return { label: option, value: option, disabled: false }
  return { label: option.label, value: option.value, disabled: Boolean(option.disabled) }
}

let uid = 0

/**
 * <uip-radio-group> — the registry RadioGroup (+ RadioGroupItem / RadioButton)
 * as ONE web component.
 *
 * Items come from light-DOM `<option value="…">Label</option>` children (read,
 * not rendered — like `uip-select`) or from the `options` property / JSON
 * attribute (React's `options` prop). Rendered in the shadow root:
 *  - `option-type="default"`: a RadioGroupItem with a label next to it. From
 *    `options` the label uses React's options-path classes; from `<option>`
 *    children it uses the registry <Label> classes (React's composed usage).
 *  - `option-type="button"`: a RadioButton per item.
 * Radios, labels (`for`) and the radiogroup all live in one shadow root, so
 * the id references resolve.
 *
 * Keyboard (Radix parity): roving tabindex; arrow keys (Up/Down when vertical,
 * Left/Right when horizontal, mirrored under `dir="rtl"`) move focus and
 * check; Home/End; `loop` wraps (default true, `loop="false"` to disable);
 * Space checks.
 *
 * Form-associated: submits `name=value`, supports `required`, resets to the
 * initial `value`. Events: `input`, `change` (read `.value`), and
 * `value-change` (React's `onValueChange`, `detail` = the new value).
 *
 * Custom composition: `slot="label-n"` (0-based item index) replaces item n's
 * label with rich markup (both `default` and `button` variants); without it
 * the option label renders as before. Per-item RadioGroupItem props (size,
 * color, hint, labelPosition, loading, hideIcon) stay data-driven — niche
 * next to the main `options` / `option-type` API. Parts: `base` (group),
 * `item` / `button` (per option), `indicator`, `label` (style from the host,
 * e.g. `class="[&::part(label)]:font-bold"`).
 */
export class UipRadioGroup extends LitElement {
  static formAssociated = true
  static shadowRootOptions = { ...LitElement.shadowRootOptions, delegatesFocus: true }
  // :host display can't be a utility class (the host has no template of its own).
  static styles = [tailwind, css`:host { display: block; }`]

  static properties = {
    value: {},
    name: { reflect: true },
    disabled: { type: Boolean, reflect: true },
    required: { type: Boolean, reflect: true },
    orientation: { reflect: true },
    loop: { converter: { fromAttribute: (v: string | null) => v !== 'false' } },
    label: {},
    hint: {},
    errorMessages: { attribute: 'error-messages' },
    error: { type: Boolean },
    density: {},
    flat: { type: Boolean },
    bordered: { type: Boolean },
    options: { type: Array },
    size: {},
    optionType: { attribute: 'option-type' },
    buttonVariant: { attribute: 'button-variant' },
    accessibleLabel: { attribute: 'aria-label' },
    childOptions: { state: true },
  }

  value = ''
  name?: string
  disabled = false
  required = false
  orientation: 'horizontal' | 'vertical' = 'vertical'
  loop = true
  label?: string
  hint?: string
  errorMessages?: string | string[]
  error = false
  density: keyof typeof groupDensityClasses = 'default'
  /** Accepted for API parity; React's RadioGroup doesn't style it either. */
  flat = false
  bordered = false
  options?: RadioOption[]
  size: ButtonSize = 'middle'
  optionType: 'default' | 'button' = 'default'
  buttonVariant: 'outline' | 'solid' = 'outline'
  accessibleLabel?: string
  private childOptions: Opt[] = []
  private defaultValue = ''
  private readonly uidBase = `uip-radio-group-${++uid}`
  private internals = this.attachInternals()
  private childObserver?: MutationObserver

  constructor() {
    super()
    new ThemeController(this)
  }

  connectedCallback() {
    super.connectedCallback()
    this.setAttribute('data-uipkge', '')
    this.setAttribute('data-slot', 'radio-group')
    this.readOptions()
    this.defaultValue = this.value
    // Frameworks render <option> children after the host connects.
    this.childObserver = new MutationObserver(() => this.readOptions())
    this.childObserver.observe(this, { childList: true, subtree: true, characterData: true, attributes: true })
  }

  disconnectedCallback() {
    super.disconnectedCallback()
    this.childObserver?.disconnect()
  }

  private readOptions() {
    this.childOptions = [...this.querySelectorAll('option')].map((o) => ({
      value: o.value,
      label: o.label,
      disabled: o.disabled,
    }))
  }

  private get fromOptionsProp() {
    return Boolean(this.options && this.options.length > 0)
  }

  private get items(): Opt[] {
    return this.fromOptionsProp ? this.options!.map(normalizeOption) : this.childOptions
  }

  protected willUpdate(changed: Map<string, unknown>) {
    if (changed.has('value') || changed.has('required')) {
      this.internals.setFormValue(this.value || null)
      if (this.required && !this.value) {
        this.internals.setValidity({ valueMissing: true }, 'Please select one of these options.', this.radios[0])
      } else {
        this.internals.setValidity({})
      }
    }
  }

  formResetCallback() {
    this.value = this.defaultValue
  }
  formDisabledCallback(disabled: boolean) {
    this.disabled = disabled
  }

  /** Focus the tabbable radio (checked one, else first enabled). */
  focus(options?: FocusOptions) {
    const tabbable = this.radios.find((r) => r.tabIndex === 0)
    if (tabbable) tabbable.focus(options)
    else super.focus(options)
  }

  private get radios() {
    return [...(this.renderRoot?.querySelectorAll<HTMLButtonElement>('[role=radio]') ?? [])]
  }

  private isDisabled(o: Opt) {
    return this.disabled || o.disabled
  }

  private check(o: Opt) {
    if (this.isDisabled(o) || o.value === this.value) return
    this.value = o.value
    this.dispatchEvent(new Event('input', { bubbles: true, composed: true }))
    this.dispatchEvent(new Event('change', { bubbles: true, composed: true }))
    this.dispatchEvent(new CustomEvent('value-change', { detail: this.value, bubbles: true, composed: true }))
  }

  private onKeyDown(e: KeyboardEvent, index: number) {
    if (e.key === 'Enter') {
      // WAI-ARIA radio groups don't check on Enter (Radix prevents it too).
      e.preventDefault()
      return
    }
    const rtl = this.matches(':dir(rtl)')
    const vertical = this.orientation === 'vertical'
    const keys: Record<string, 'prev' | 'next' | 'first' | 'last'> = vertical
      ? { ArrowUp: 'prev', ArrowDown: 'next' }
      : rtl
        ? { ArrowRight: 'prev', ArrowLeft: 'next' }
        : { ArrowLeft: 'prev', ArrowRight: 'next' }
    Object.assign(keys, { Home: 'first', End: 'last', PageUp: 'first', PageDown: 'last' })
    const intent = keys[e.key]
    if (!intent) return
    e.preventDefault()
    const items = this.items
    const enabled = items.map((o, i) => (this.isDisabled(o) ? -1 : i)).filter((i) => i >= 0)
    if (!enabled.length) return
    let target: number
    if (intent === 'first') target = enabled[0]
    else if (intent === 'last') target = enabled[enabled.length - 1]
    else {
      const pos = enabled.indexOf(index)
      let next = intent === 'next' ? pos + 1 : pos - 1
      if (next < 0) next = this.loop ? enabled.length - 1 : 0
      if (next >= enabled.length) next = this.loop ? 0 : enabled.length - 1
      target = enabled[next]
    }
    this.check(items[target])
    this.radios[target]?.focus()
  }

  private renderRadio(o: Opt, i: number, tabbable: number, slot: string, classes: string, content: unknown) {
    const checked = o.value === this.value
    const disabled = this.isDisabled(o)
    return html`<button
      id=${`${this.uidBase}-${i}`}
      type="button"
      role="radio"
      part=${slot === 'radio-button' ? 'button' : 'item'}
      data-uipkge=""
      data-slot=${slot}
      aria-checked=${checked ? 'true' : 'false'}
      data-state=${checked ? 'checked' : 'unchecked'}
      data-orientation=${this.orientation}
      ?data-disabled=${disabled}
      ?disabled=${disabled}
      value=${o.value}
      tabindex=${i === tabbable ? 0 : -1}
      class=${classes}
      @click=${() => this.check(o)}
      @keydown=${(e: KeyboardEvent) => this.onKeyDown(e, i)}
    >
      ${content}
    </button>`
  }

  private renderItem(o: Opt, i: number, tabbable: number) {
    const checked = o.value === this.value
    const indicator = checked
      ? html`<span
          part="indicator"
          data-state="checked"
          ?data-disabled=${this.isDisabled(o)}
          data-uipkge=""
          data-slot="radio-group-indicator"
          class="relative flex items-center justify-center"
          >${icon(Circle, 'circle', indicatorIconClasses)}</span
        >`
      : nothing
    const radio = html`<div class=${cn('flex flex-col', itemDensityClasses.default)}>
      <div class="flex items-center">
        ${this.renderRadio(o, i, tabbable, 'radio-group-item', itemClasses, indicator)}
      </div>
    </div>`
    const labelClass = this.fromOptionsProp
      ? cn('cursor-pointer text-sm font-medium select-none', o.disabled && 'cursor-not-allowed opacity-50')
      : labelComponentClasses
    return html`<div class="flex items-center gap-2">
      ${radio}
      <label
        part="label"
        for=${`${this.uidBase}-${i}`}
        data-slot=${this.fromOptionsProp ? nothing : 'label'}
        class=${labelClass}
        ><slot name=${`label-${i}`}>${o.label}</slot></label
      >
    </div>`
  }

  private renderButton(o: Opt, i: number, tabbable: number) {
    const groupClasses =
      this.orientation === 'vertical'
        ? 'rounded-md w-full justify-start'
        : cn('rounded-none first:rounded-l-md last:rounded-r-md', 'border-l-0 first:border-l', '-ml-px first:ml-0')
    const classes = cn(
      'inline-flex items-center justify-center gap-2 font-medium whitespace-nowrap transition-colors duration-200',
      'focus-visible:border-ring focus-visible:ring-ring/50 outline-none focus-visible:ring-[3px]',
      'disabled:cursor-not-allowed disabled:opacity-50',
      buttonSizeClasses[this.size] ?? buttonSizeClasses.middle,
      buttonVariantClasses[this.buttonVariant] ?? buttonVariantClasses.outline,
      groupClasses,
    )
    return this.renderRadio(
      o,
      i,
      tabbable,
      'radio-button',
      classes,
      html`<slot name=${`label-${i}`}>${o.label || o.value}</slot>`,
    )
  }

  render() {
    const items = this.items
    const checkedIndex = items.findIndex((o) => o.value === this.value && !this.isDisabled(o))
    const tabbable = checkedIndex >= 0 ? checkedIndex : items.findIndex((o) => !this.isDisabled(o))
    const msgs = this.errorMessages
    const hasError = Boolean(this.error) || Boolean(msgs && (typeof msgs === 'string' ? msgs : msgs.length > 0))
    const isButton = this.optionType === 'button'
    const labelId = `${this.uidBase}-label`

    return html`<div class="flex flex-col gap-2">
      ${this.label ? html`<label id=${labelId} class="text-sm font-medium">${this.label}</label>` : nothing}
      ${this.hint && !hasError ? html`<p class="text-muted-foreground text-xs">${this.hint}</p>` : nothing}
      <div
        part="base"
        role="radiogroup"
        aria-required=${this.required ? 'true' : 'false'}
        aria-orientation=${this.orientation}
        aria-labelledby=${this.label && !this.accessibleLabel ? labelId : nothing}
        aria-label=${this.accessibleLabel ?? nothing}
        data-slot="radio-group"
        data-orientation=${this.orientation}
        ?data-disabled=${this.disabled}
        class=${cn(
          'grid gap-3',
          this.orientation === 'horizontal' && 'flex flex-row items-center gap-4',
          isButton && this.orientation === 'horizontal' && 'flex flex-row items-stretch gap-0',
          isButton && this.orientation === 'vertical' && 'flex flex-col items-stretch gap-0',
          !isButton && (groupDensityClasses[this.density] ?? groupDensityClasses.default),
          this.bordered && 'rounded-lg border p-4',
        )}
      >
        ${items.map((o, i) => (isButton ? this.renderButton(o, i, tabbable) : this.renderItem(o, i, tabbable)))}
      </div>
      ${hasError
        ? html`<div class="flex flex-col gap-0.5">
            ${(typeof msgs === 'string' ? [msgs] : (msgs ?? [])).map(
              (m) => html`<p class="text-destructive text-xs">${m}</p>`,
            )}
          </div>`
        : nothing}
    </div>`
  }
}

customElements.get('uip-radio-group') || customElements.define('uip-radio-group', UipRadioGroup)

declare global {
  interface HTMLElementTagNameMap {
    'uip-radio-group': UipRadioGroup
  }
}

// packages/angular/components/radio-group/radio-group.component.ts
import {
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnDestroy,
  Output,
  booleanAttribute,
  forwardRef,
  inject,
  signal,
  ChangeDetectionStrategy,
} from '@angular/core'
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms'
import { cn } from '@/lib/utils'

export type RadioOption = string | { label: string; value: string; disabled?: boolean }
export type RadioOrientation = 'horizontal' | 'vertical'
export type RadioDensity = 'compact' | 'default' | 'comfortable'
/** Button-style radio sizes (group `size`, RadioButton `size`). */
export type RadioButtonSize = 'small' | 'middle' | 'large'
export type RadioItemDotSize = 'sm' | 'md' | 'lg'
export type RadioButtonVariant = 'outline' | 'solid'
export type RadioColor = 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'info' | (string & {})

export interface NormalizedRadioOption {
  label: string
  value: string
  disabled?: boolean
}

export function normalizeRadioOption(option: RadioOption): NormalizedRadioOption {
  if (typeof option === 'string') return { label: option, value: option }
  return option
}

function optionalBoolean(v: unknown): boolean | undefined {
  return v === undefined || v === null ? undefined : booleanAttribute(v)
}

function hasErrors(error: boolean, errorMessages: string | string[] | undefined): boolean {
  return (
    error || Boolean(errorMessages && (typeof errorMessages === 'string' ? errorMessages : errorMessages.length > 0))
  )
}

function toList(errorMessages: string | string[] | undefined): string[] {
  if (!errorMessages) return []
  return typeof errorMessages === 'string' ? [errorMessages] : errorMessages
}

const GROUP_DENSITY_CLASSES: Record<RadioDensity, string> = {
  compact: 'gap-1',
  default: 'gap-3',
  comfortable: 'gap-4',
}

const ITEM_DENSITY_CLASSES: Record<RadioDensity, string> = {
  compact: 'gap-1',
  default: 'gap-2',
  comfortable: 'gap-3',
}

const ITEM_SIZE_CLASSES: Record<RadioItemDotSize, string> = {
  sm: 'size-3.5',
  md: 'size-4',
  lg: 'size-5',
}

const INDICATOR_SIZES: Record<RadioItemDotSize, string> = {
  sm: 'size-1.5',
  md: 'size-2',
  lg: 'size-2.5',
}

const ITEM_COLOR_CLASSES: Record<string, string> = {
  primary: 'data-[state=checked]:border-primary',
  secondary: 'data-[state=checked]:border-secondary',
  success: 'data-[state=checked]:border-success data-[state=checked]:text-success',
  warning: 'data-[state=checked]:border-warning data-[state=checked]:text-warning',
  error: 'data-[state=checked]:border-destructive data-[state=checked]:text-destructive',
  info: 'data-[state=checked]:border-info data-[state=checked]:text-info',
}

const BUTTON_SIZE_CLASSES: Record<RadioButtonSize, string> = {
  small: 'h-7 px-2.5 text-xs',
  middle: 'h-8 px-4 text-sm',
  large: 'h-10 px-4.5 text-base',
}

const BUTTON_VARIANT_CLASSES: Record<RadioButtonVariant, string> = {
  outline: cn(
    'border border-input bg-transparent text-foreground hover:text-foreground hover:bg-muted/50',
    'data-[state=checked]:border-primary data-[state=checked]:text-primary',
    'disabled:hover:bg-transparent',
  ),
  solid: cn(
    'border border-input bg-transparent text-foreground hover:text-foreground hover:bg-muted/50',
    'data-[state=checked]:border-primary data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground',
    'disabled:hover:bg-transparent',
  ),
}

/** Radix RovingFocusGroup key -> focus intent. */
const KEY_TO_INTENT: Record<string, 'first' | 'last' | 'prev' | 'next'> = {
  ArrowLeft: 'prev',
  ArrowUp: 'prev',
  ArrowRight: 'next',
  ArrowDown: 'next',
  PageUp: 'first',
  Home: 'first',
  PageDown: 'last',
  End: 'last',
}
const ARROW_KEYS = ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight']

/** What the group needs from each radio (RadioGroupItem / RadioButton). */
interface RadioItem {
  readonly value: string
  readonly isDisabled: boolean
  readonly hostEl: HTMLElement
  focusTarget(): HTMLElement | null
}

/**
 * Angular port of the React RadioGroupItem: a Radix radio `<button role="radio">` with the
 * circle indicator, plus optional label (before / after), hint and error messages. Reads
 * checked / disabled state from the enclosing RadioGroup. `class` / `id` go to the button.
 */
@Component({
  changeDetection: ChangeDetectionStrategy.Eager,
  selector: 'ui-radio-group-item, [ui-radio-group-item], ui-radio-item',
  standalone: true,
  host: {
    // [attr.class], not [class]: [class] merges in the consumer's static class attribute, which
    // belongs to the inner root only.
    '[attr.class]': 'wrapperClass',
    // id belongs to the button; keep a static id off the host so <label for> finds the button.
    '[attr.id]': 'null',
  },
  template: `
    <div class="flex items-center">
      @if (label && labelPosition === 'before') {
        <label [attr.for]="id" [class]="labelClass('mr-2')">{{ label }}</label>
      }
      <button
        type="button"
        role="radio"
        data-uipkge=""
        data-slot="radio-group-item"
        [attr.id]="id"
        [attr.value]="value"
        [attr.aria-checked]="checked"
        [attr.aria-busy]="loading || null"
        [attr.aria-invalid]="hasError || null"
        [attr.data-state]="checked ? 'checked' : 'unchecked'"
        [attr.data-disabled]="isDisabled ? '' : null"
        [attr.data-orientation]="group?.orientation"
        [attr.tabindex]="group ? group.tabIndexFor(this) : null"
        [disabled]="isDisabled"
        [class]="buttonClass"
        (click)="onClick()"
        (focus)="group?.onItemFocus(this)"
        (keydown)="onKeydown($event)"
      >
        @if (checked) {
          <span
            data-uipkge=""
            data-slot="radio-group-indicator"
            data-state="checked"
            [attr.data-disabled]="isDisabled ? '' : null"
            class="relative flex items-center justify-center"
          >
            @if (!hideIcon) {
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                [attr.class]="indicatorClass"
                aria-hidden="true"
              >
                <circle cx="12" cy="12" r="10" />
              </svg>
            }
          </span>
        }
      </button>
      @if (label && labelPosition === 'after') {
        <label [attr.for]="id" [class]="labelClass('ml-2')">{{ label }}</label>
      }
    </div>
    @if (hint && !hasError) {
      <p class="text-muted-foreground ml-6 text-xs">{{ hint }}</p>
    }
    @if (hasError) {
      <div class="ml-6 flex flex-col gap-0.5">
        @for (msg of errorList; track $index) {
          <p class="text-destructive text-xs">{{ msg }}</p>
        }
      </div>
    }
  `,
})
export class UiRadioGroupItemComponent implements RadioItem, OnDestroy {
  // The group class is declared below (it imports these parts); resolved at construction time.
  readonly group: UiRadioGroupComponent | null = inject(
    forwardRef(() => UiRadioGroupComponent),
    { optional: true },
  )
  readonly hostEl: HTMLElement = inject(ElementRef).nativeElement

  @Input() value = ''
  @Input() id?: string
  @Input({ transform: optionalBoolean }) disabled?: boolean
  @Input() size: RadioItemDotSize = 'md'
  @Input() color: RadioColor = 'primary'
  @Input() label?: string
  @Input() hint?: string
  @Input() errorMessages?: string | string[]
  @Input({ transform: booleanAttribute }) error = false
  @Input() density: RadioDensity = 'default'
  @Input() labelPosition: 'before' | 'after' = 'after'
  @Input({ transform: booleanAttribute }) loading = false
  @Input({ transform: booleanAttribute }) hideIcon = false
  @Input('class') className?: string

  constructor() {
    this.group?.register(this)
  }

  ngOnDestroy(): void {
    this.group?.unregister(this)
  }

  get checked(): boolean {
    return this.group?.isChecked(this.value) ?? false
  }

  /** React: loading || (disabled ?? group.disabled); Radix also ORs the group's disabled. */
  get isDisabled(): boolean {
    return this.loading || (this.disabled ?? this.group?.disabled ?? false) || !!this.group?.disabled
  }

  get hasError(): boolean {
    return hasErrors(this.error, this.errorMessages)
  }

  get errorList(): string[] {
    return toList(this.errorMessages)
  }

  get wrapperClass(): string {
    return cn('flex flex-col', ITEM_DENSITY_CLASSES[this.density])
  }

  get buttonClass(): string {
    return cn(
      'border-input text-primary focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:bg-input/30 aspect-square shrink-0 rounded-full border shadow-sm transition-colors duration-200 outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50',
      ITEM_SIZE_CLASSES[this.size],
      ITEM_COLOR_CLASSES[this.color] || ITEM_COLOR_CLASSES['primary'],
      this.hasError && 'border-destructive',
      this.loading && 'opacity-50',
      this.className,
    )
  }

  get indicatorClass(): string {
    return cn(
      'lucide lucide-circle',
      'absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 fill-current text-current',
      INDICATOR_SIZES[this.size],
    )
  }

  labelClass(side: string): string {
    return cn(
      side,
      cn(
        'cursor-pointer text-sm leading-none font-medium select-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
        this.hasError ? 'text-destructive' : '',
        this.isDisabled && 'cursor-not-allowed opacity-50',
      ),
    )
  }

  focusTarget(): HTMLElement | null {
    return this.hostEl.querySelector<HTMLElement>('button[role="radio"]')
  }

  onClick(): void {
    if (!this.isDisabled && !this.checked) this.group?.select(this.value)
  }

  onKeydown(event: KeyboardEvent): void {
    this.group?.onItemKeydown(this, event)
  }
}

/**
 * Angular port of the React RadioButton (Ant-style button radio). The host is the Radix
 * radio itself: use `<button ui-radio-button>` for React's exact DOM, or `<ui-radio-button>`
 * (focusable role="radio", Space selects). Size / variant / disabled default to the group's.
 * Content: projected children, else `label`, else `value` (React `children ?? label ?? value`).
 */
@Component({
  changeDetection: ChangeDetectionStrategy.Eager,
  selector: 'ui-radio-button, [ui-radio-button]',
  standalone: true,
  host: {
    '[attr.type]': 'isNativeButton ? "button" : null',
    '[attr.role]': '"radio"',
    '[attr.aria-checked]': 'checked',
    '[attr.aria-disabled]': '!isNativeButton && isDisabled ? "true" : null',
    '[attr.data-state]': 'checked ? "checked" : "unchecked"',
    '[attr.data-disabled]': 'isDisabled ? "" : null',
    '[attr.data-orientation]': 'group?.orientation',
    '[attr.disabled]': 'isNativeButton && isDisabled ? "" : null',
    '[attr.value]': 'value',
    '[attr.tabindex]': 'group ? group.tabIndexFor(this) : isNativeButton ? null : 0',
    '[attr.data-uipkge]': '""',
    '[attr.data-slot]': '"radio-button"',
    '[class]': 'hostClass',
    '(click)': 'onClick()',
    '(focus)': 'group?.onItemFocus(this)',
    '(keydown)': 'onKeydown($event)',
  },
  template: `<ng-content>{{ label ?? value }}</ng-content>`,
})
export class UiRadioButtonComponent implements RadioItem, OnDestroy {
  // The group class is declared below (it imports these parts); resolved at construction time.
  readonly group: UiRadioGroupComponent | null = inject(
    forwardRef(() => UiRadioGroupComponent),
    { optional: true },
  )
  readonly hostEl: HTMLElement = inject(ElementRef).nativeElement
  readonly isNativeButton = this.hostEl.tagName === 'BUTTON'

  @Input() value = ''
  @Input({ transform: optionalBoolean }) disabled?: boolean
  @Input() size?: RadioButtonSize
  @Input() variant?: RadioButtonVariant
  @Input() label?: string
  @Input('class') className?: string

  constructor() {
    this.group?.register(this)
  }

  ngOnDestroy(): void {
    this.group?.unregister(this)
  }

  get checked(): boolean {
    return this.group?.isChecked(this.value) ?? false
  }

  get isDisabled(): boolean {
    return (this.disabled ?? this.group?.disabled ?? false) || !!this.group?.disabled
  }

  get hostClass(): string {
    const size = this.size ?? this.group?.size ?? 'middle'
    const variant = this.variant ?? this.group?.buttonVariant ?? 'outline'
    const groupClasses =
      this.group?.orientation === 'vertical'
        ? 'rounded-md w-full justify-start'
        : cn('rounded-none first:rounded-l-md last:rounded-r-md', 'border-l-0 first:border-l', '-ml-px first:ml-0')
    return cn(
      'inline-flex items-center justify-center gap-2 font-medium whitespace-nowrap transition-colors duration-200',
      'focus-visible:border-ring focus-visible:ring-ring/50 outline-none focus-visible:ring-[3px]',
      'disabled:cursor-not-allowed disabled:opacity-50',
      BUTTON_SIZE_CLASSES[size],
      BUTTON_VARIANT_CLASSES[variant],
      groupClasses,
      // A custom-element host never matches :disabled, so mirror the disabled look via data-disabled.
      !this.isNativeButton && 'data-[disabled]:cursor-not-allowed data-[disabled]:opacity-50',
      this.className,
    )
  }

  focusTarget(): HTMLElement {
    return this.hostEl
  }

  onClick(): void {
    if (!this.isDisabled && !this.checked) this.group?.select(this.value)
  }

  onKeydown(event: KeyboardEvent): void {
    // Native buttons turn Space into a click; the custom-element host needs it done here.
    if (!this.isNativeButton && event.key === ' ') {
      event.preventDefault()
      this.onClick()
      return
    }
    this.group?.onItemKeydown(this, event)
  }
}

/**
 * Angular port of the React RadioGroup (Radix RadioGroup). The host is React's outer
 * `flex flex-col gap-2` wrapper (label, hint, errors); inside it the `role="radiogroup"`
 * root holds `options` or projected RadioGroupItem / RadioButton parts, which read the
 * group's value / disabled / size / variant / orientation through DI.
 *
 * Model is React's `value` / `defaultValue` / `valueChange` (`[(value)]`) plus
 * NG_VALUE_ACCESSOR. Keyboard is Radix roving focus: arrow keys move focus and select
 * (Left/Right ignored when vertical, Up/Down when horizontal, rtl flips), Home / End /
 * PageUp / PageDown move focus only, `loop` wraps, disabled items are skipped, and only
 * the checked (or first enabled) radio is in the Tab order. `class` goes to the root.
 */
@Component({
  changeDetection: ChangeDetectionStrategy.Eager,
  selector: 'ui-radio-group, [ui-radio-group]',
  standalone: true,
  exportAs: 'uiRadioGroup',
  imports: [UiRadioGroupItemComponent, UiRadioButtonComponent],
  providers: [{ provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => UiRadioGroupComponent), multi: true }],
  host: { '[attr.class]': '"flex flex-col gap-2"' },
  template: `
    @if (label) {
      <label class="text-sm font-medium">{{ label }}</label>
    }
    @if (hint && !hasError) {
      <p class="text-muted-foreground text-xs">{{ hint }}</p>
    }
    <div
      role="radiogroup"
      data-slot="radio-group"
      [attr.aria-required]="required || null"
      [attr.aria-orientation]="orientation"
      [attr.data-orientation]="orientation"
      [attr.data-disabled]="disabled ? '' : null"
      [attr.dir]="dir"
      [class]="rootClass"
    >
      @if (normalizedOptions.length > 0) {
        @if (optionType === 'button') {
          @for (opt of normalizedOptions; track opt.value) {
            <button ui-radio-button [value]="opt.value" [disabled]="opt.disabled" [label]="opt.label"></button>
          }
        } @else {
          @for (opt of normalizedOptions; track opt.value) {
            <div class="flex items-center gap-2">
              <ui-radio-group-item [id]="opt.value" [value]="opt.value" [disabled]="opt.disabled" />
              <label [attr.for]="opt.value" [class]="optionLabelClass(opt)">{{ opt.label }}</label>
            </div>
          }
        }
      } @else {
        <ng-content />
      }
    </div>
    @if (hasError) {
      <div class="flex flex-col gap-0.5">
        @for (msg of errorList; track $index) {
          <p class="text-destructive text-xs">{{ msg }}</p>
        }
      </div>
    }
  `,
})
export class UiRadioGroupComponent implements ControlValueAccessor {
  // Zoneless-safe: form writes happen outside template events, so schedule a repaint.
  private readonly cdr = inject(ChangeDetectorRef)
  private readonly _valueProp = signal<string | undefined>(undefined)
  private readonly _internal = signal<string | null>(null)
  private readonly items: RadioItem[] = []
  /** Radix RovingFocusGroup currentTabStopId: the last focused radio. */
  private currentTabStop: RadioItem | null = null

  /** Controlled value (React `value`). Reading it returns the resolved value. */
  @Input()
  set value(v: string | null | undefined) {
    this._valueProp.set(v ?? undefined)
  }
  get value(): string | undefined {
    return this._valueProp() ?? this._internal() ?? this.defaultValue
  }
  @Input() defaultValue?: string
  @Output() valueChange = new EventEmitter<string>()

  // Signal-backed: projected items live in the parent's view, so a form's disable() must
  // reach them without a parent re-render (zoneless).
  private readonly _disabled = signal(false)
  @Input({ transform: booleanAttribute })
  set disabled(v: boolean) {
    this._disabled.set(v)
  }
  get disabled(): boolean {
    return this._disabled()
  }
  @Input() orientation: RadioOrientation = 'vertical'
  @Input({ transform: booleanAttribute }) loop = true
  @Input() label?: string
  @Input() hint?: string
  @Input() errorMessages?: string | string[]
  @Input({ transform: booleanAttribute }) error = false
  @Input() density: RadioDensity = 'default'
  @Input({ transform: booleanAttribute }) flat = false
  @Input({ transform: booleanAttribute }) bordered = false
  @Input() dir: 'ltr' | 'rtl' = 'ltr'
  @Input() options?: RadioOption[]
  @Input() size: RadioButtonSize = 'middle'
  @Input() optionType: 'default' | 'button' = 'default'
  @Input() buttonVariant: RadioButtonVariant = 'outline'
  @Input({ transform: booleanAttribute }) required = false
  @Input() name?: string
  @Input('class') className?: string

  private onChange: (v: string) => void = () => {}
  private onTouched: () => void = () => {}

  get normalizedOptions(): NormalizedRadioOption[] {
    return (this.options ?? []).map(normalizeRadioOption)
  }

  get hasError(): boolean {
    return hasErrors(this.error, this.errorMessages)
  }

  get errorList(): string[] {
    return toList(this.errorMessages)
  }

  get rootClass(): string {
    return cn(
      'grid gap-3',
      this.orientation === 'horizontal' && 'flex flex-row items-center gap-4',
      this.optionType === 'button' && this.orientation === 'horizontal' && 'flex flex-row items-stretch gap-0',
      this.optionType === 'button' && this.orientation === 'vertical' && 'flex flex-col items-stretch gap-0',
      this.optionType !== 'button' && GROUP_DENSITY_CLASSES[this.density],
      this.bordered && 'rounded-lg border p-4',
      this.className,
    )
  }

  optionLabelClass(opt: NormalizedRadioOption): string {
    return cn('cursor-pointer text-sm font-medium select-none', opt.disabled && 'cursor-not-allowed opacity-50')
  }

  isChecked(value: string): boolean {
    return this.value !== undefined && this.value === value
  }

  select(value: string): void {
    if (this.disabled || value === this.value) return
    this._internal.set(value)
    this.onChange(value)
    this.onTouched()
    this.valueChange.emit(value)
  }

  // ---- roving focus (Radix RovingFocusGroup) ----

  register(item: RadioItem): void {
    this.items.push(item)
  }

  unregister(item: RadioItem): void {
    const i = this.items.indexOf(item)
    if (i >= 0) this.items.splice(i, 1)
    if (this.currentTabStop === item) this.currentTabStop = null
  }

  private ordered(): RadioItem[] {
    return [...this.items].sort((a, b) =>
      a.hostEl.compareDocumentPosition(b.hostEl) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1,
    )
  }

  /** 0 for the one radio in the Tab order (last focused, else checked, else first enabled). */
  tabIndexFor(item: RadioItem): number {
    if (item.isDisabled) return -1
    const enabled = this.ordered().filter((i) => !i.isDisabled)
    const stop =
      (this.currentTabStop && enabled.includes(this.currentTabStop) ? this.currentTabStop : null) ??
      enabled.find((i) => this.isChecked(i.value)) ??
      enabled[0]
    return stop === item ? 0 : -1
  }

  onItemFocus(item: RadioItem): void {
    this.currentTabStop = item
  }

  onItemKeydown(item: RadioItem, event: KeyboardEvent): void {
    // WAI-ARIA: radio groups don't activate items on Enter.
    if (event.key === 'Enter') {
      event.preventDefault()
      return
    }
    if (event.target !== event.currentTarget) return
    const key =
      this.dir === 'rtl' && event.key === 'ArrowLeft'
        ? 'ArrowRight'
        : this.dir === 'rtl' && event.key === 'ArrowRight'
          ? 'ArrowLeft'
          : event.key
    if (this.orientation === 'vertical' && (key === 'ArrowLeft' || key === 'ArrowRight')) return
    if (this.orientation === 'horizontal' && (key === 'ArrowUp' || key === 'ArrowDown')) return
    const intent = KEY_TO_INTENT[key]
    if (!intent || event.metaKey || event.ctrlKey || event.altKey || event.shiftKey) return
    event.preventDefault()
    let candidates = this.ordered().filter((i) => !i.isDisabled)
    if (intent === 'last') candidates.reverse()
    if (intent === 'prev' || intent === 'next') {
      if (intent === 'prev') candidates.reverse()
      const start = candidates.indexOf(item) + 1
      candidates = this.loop
        ? candidates.map((_, i) => candidates[(start + i) % candidates.length]!)
        : candidates.slice(start)
    }
    const target = candidates[0]?.focusTarget()
    if (!target) return
    target.focus()
    // Radix RadioGroupItem: focus that arrives from an arrow key also checks the radio.
    if (ARROW_KEYS.includes(event.key)) target.click()
  }

  writeValue(v: string | null): void {
    this._internal.set(v ?? null)
    this.cdr.markForCheck()
  }

  registerOnChange(fn: (v: string) => void): void {
    this.onChange = fn
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled
    this.cdr.markForCheck()
  }
}
