// packages/svelte/components/treemap-chart/TreemapChart.svelte
<script lang="ts" module>
  import type { HTMLAttributes } from 'svelte/elements'

  export interface TreemapNode {
    name: string
    value?: number
    children?: TreemapNode[]
  }

  export interface TreemapChartProps extends HTMLAttributes<HTMLDivElement> {
    data: TreemapNode[]
    height?: number | string
    /** Show breadcrumb at top when drilling into a sub-tree. Default false. */
    showBreadcrumb?: boolean
    option?: any
    /** Accessible name announced for the chart image. Defaults to "Chart". */
    ariaLabel?: string
    ref?: HTMLDivElement | null
  }
</script>

<script lang="ts">
  import { onMount } from 'svelte'
  import { init, use, type ECharts } from 'echarts/core'
  import { CanvasRenderer } from 'echarts/renderers'
  import { TreemapChart as EChartsTreemapChart } from 'echarts/charts'
  // VisualMapComponent registered alongside Tooltip so consumers can hand a
  // `visualMap` config via the option escape hatch (color-by-value variant).
  import { TooltipComponent, VisualMapComponent } from 'echarts/components'
  import { cn } from '$lib/utils'
  import {
    getChartColors,
    getChartTextColor,
    getChartTooltipBg,
    getChartTooltipBorder,
    getChartTooltipText,
    toRgba,
  } from './chart-theme'

  use([CanvasRenderer, EChartsTreemapChart, TooltipComponent, VisualMapComponent])

  let {
    data,
    height = 320,
    showBreadcrumb = false,
    option,
    class: className,
    ariaLabel,
    ref = $bindable(null),
    ...restProps
  }: TreemapChartProps = $props()

  // Theme version: bumped on mount and whenever `<html>` class/style changes
  // (the typical dark-mode pivot) so the derived option re-resolves
  // CSS-driven colors and the chart re-paints.
  let themeKey = $state(0)
  onMount(() => {
    themeKey++
    const mo = new MutationObserver(() => themeKey++)
    mo.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['class', 'style', 'data-theme'],
    })
    return () => mo.disconnect()
  })

  const mergedOption = $derived.by(() => {
    void themeKey
    const textColor = getChartTextColor()
    const series = [
      {
        type: 'treemap',
        // Explicit left/top/right/bottom anchor the layout at 0,0 of the
        // container. Without these, ECharts centres the treemap and the
        // (invisible) breadcrumb still reserves ~22px at the top -- shows
        // up as a phantom gap above the first rect.
        left: 0,
        top: 0,
        right: 0,
        bottom: 0,
        width: 'auto',
        height: 'auto',
        roam: false,
        nodeClick: false,
        breadcrumb: { show: showBreadcrumb, height: 0 },
        label: {
          show: true,
          formatter: ({ name, value }: any) => (value ? `{b|${name}}\n{v|${value}}` : name),
          rich: {
            b: { color: textColor, fontSize: 11, fontWeight: 600, lineHeight: 14 },
            v: { color: toRgba(textColor, 0.85), fontSize: 10, fontWeight: 500, lineHeight: 12 },
          },
          overflow: 'truncate',
          ellipsis: '…',
        },
        labelLayout: { hideOverlap: false },
        upperLabel: { show: false },
        // gapWidth carves out the tile separators; an explicit borderColor
        // would render as a contrasting stripe on the consumer's theme
        // (white in dark mode, etc.). The gap reads as separation already.
        itemStyle: { borderWidth: 0, gapWidth: 2 },
        // The earlier `levels` config carried `colorSaturation` per depth
        // for nested trees, but it also implicitly cleared the series
        // `label` config at each level -- which meant flat data (the
        // common case) rendered as untitled coloured rectangles. Apply
        // saturation directly on the series so a single level config
        // doesn't blow away the labels.
        colorSaturation: [0.45, 0.7],
        data,
      },
    ]

    // Per-index series merge — partial overrides keep computed `type`/`data`.
    const userOption: any = option ?? {}
    const { series: userSeries, ...userRest } = userOption
    const mergedSeries = Array.isArray(userSeries)
      ? series.map((s, i) => ({ ...s, ...(userSeries[i] ?? {}) }))
      : series

    return {
      color: getChartColors(),
      tooltip: {
        formatter: (info: any) => {
          const parts = info.treePathInfo.map((n: any) => n.name).filter(Boolean)
          return `<strong>${parts.join(' / ')}</strong><br>${info.value?.toLocaleString?.() ?? info.value}`
        },
        backgroundColor: getChartTooltipBg(),
        borderColor: getChartTooltipBorder(),
        textStyle: { color: getChartTooltipText(), fontSize: 12 },
      },
      series: mergedSeries,
      ...userRest,
    }
  })

  const heightStyle = $derived(/^\d+$/.test(String(height)) ? `${height}px` : String(height))

  let container = $state<HTMLDivElement | null>(null)
  let chart: ECharts | null = null

  onMount(() => {
    if (!container) return
    const c = init(container)
    chart = c
    c.setOption(mergedOption)
    const ro = new ResizeObserver(() => c.resize())
    ro.observe(container)
    return () => {
      ro.disconnect()
      c.dispose()
      chart = null
    }
  })

  $effect(() => {
    const opt = mergedOption
    chart?.setOption(opt)
  })
</script>

<div
  bind:this={ref}
  data-uipkge
  data-slot="treemap-chart"
  role="img"
  tabindex="0"
  aria-label={ariaLabel || 'Chart'}
  style="height: {heightStyle}"
  class={cn('w-full focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none', className)}
  {...restProps}
>
  <div bind:this={container} class="size-full"></div>
</div>

// packages/angular/components/charts/treemap-chart/treemap-chart.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  SimpleChanges,
  ViewChild,
  ChangeDetectionStrategy,
} from '@angular/core'
import type * as echarts from 'echarts/core'
import { cn } from '@/lib/utils'
import {
  getChartColors,
  getChartTextColor,
  getChartTooltipBg,
  getChartTooltipBorder,
  getChartTooltipText,
  mergeOptionBlock,
  toRgba,
} from '../use-chart-theme'

export interface TreemapNode {
  name: string
  value?: number
  children?: TreemapNode[]
}

/**
 * Angular port of the UIPKGE TreemapChart — nested rectangles sized by
 * value. Standalone, theme-aware.
 */
@Component({
  changeDetection: ChangeDetectionStrategy.Eager,
  selector: 'ui-treemap-chart, [ui-treemap-chart]',
  standalone: true,
  host: {
    '[attr.data-slot]': '"treemap-chart"',
    '[attr.data-uipkge]': '""',
    '[class]': 'hostClass',
    '[attr.role]': '"img"',
    '[attr.aria-label]': 'ariaLabel || "Chart"',
    '[attr.tabindex]': '0',
    '[style.height]': 'heightStyle',
  },
  template: `<div #chartEl class="size-full"></div>`,
})
export class UiTreemapChartComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() data: TreemapNode[] = []
  /** Show breadcrumb at top when drilling into a sub-tree. Default false. */
  @Input() showBreadcrumb = false
  /** Leaf corner rounding in px (Angular-only styling knob). Default 4. */
  @Input() radius = 4
  @Input() height: number | string = 320
  @Input() option?: Record<string, unknown>
  /** Accessible name announced for the chart image. Defaults to "Chart". */
  @Input() ariaLabel?: string
  @Input('class') className?: string

  leafCount(): number {
    let n = 0
    const walk = (nodes: TreemapNode[]) => {
      for (const node of nodes) {
        if ((node.children ?? []).length) walk(node.children as TreemapNode[])
        else n++
      }
    }
    walk(this.data)
    return n
  }
  @ViewChild('chartEl', { static: false }) chartEl?: ElementRef<HTMLDivElement>

  private chart: echarts.ECharts | null = null
  private unsubscribeTheme: (() => void) | null = null

  get hostClass(): string {
    return cn('block focus-visible:ring-ring w-full focus-visible:ring-2 focus-visible:outline-none', this.className)
  }

  get heightStyle(): string {
    return /^\d+$/.test(String(this.height)) ? `${this.height}px` : String(this.height)
  }

  /** Build the merged ECharts option (pure — no DOM needed, unit-testable). */
  getOption(): Record<string, unknown> {
    const colors = getChartColors()
    const textColor = getChartTextColor()
    const series = [
      {
        type: 'treemap',
        // Explicit anchors keep the layout at 0,0 — without these the (invisible)
        // breadcrumb reserves ~22px at the top (Vue parity comment).
        left: 0,
        top: 0,
        right: 0,
        bottom: 0,
        width: 'auto',
        height: 'auto',
        roam: false,
        nodeClick: false,
        breadcrumb: { show: this.showBreadcrumb, height: 0 },
        label: {
          show: true,
          formatter: ({ name, value }: any) => (value ? `{b|${name}}\n{v|${value}}` : name),
          rich: {
            b: { color: textColor, fontSize: 11, fontWeight: 600, lineHeight: 14 },
            v: { color: toRgba(textColor, 0.85), fontSize: 10, fontWeight: 500, lineHeight: 12 },
          },
          overflow: 'truncate',
          ellipsis: '…',
        },
        labelLayout: { hideOverlap: false },
        upperLabel: { show: false },
        // gapWidth reads as separation already; an explicit borderColor would render
        // as a contrasting stripe on the consumer's theme (Vue parity comment).
        itemStyle: { borderWidth: 0, gapWidth: 2, borderRadius: this.radius },
        colorSaturation: [0.45, 0.7],
        data: this.data,
      },
    ]
    const userOption: Record<string, any> = this.option ?? {}
    const { series: userSeries, tooltip: userTooltip, ...userRest } = userOption
    // Per-index series merge — partial overrides keep computed `type`/`data` (React/Vue parity).
    const mergedSeries = Array.isArray(userSeries) ? series.map((s, i) => ({ ...s, ...(userSeries[i] ?? {}) })) : series
    return {
      color: colors,
      tooltip: mergeOptionBlock(
        {
          formatter: (info: any) => {
            const parts = info.treePathInfo.map((n: any) => n.name).filter(Boolean)
            return `<strong>${parts.join(' / ')}</strong><br>${info.value?.toLocaleString?.() ?? info.value}`
          },
          backgroundColor: getChartTooltipBg(),
          borderColor: getChartTooltipBorder(),
          textStyle: { color: getChartTooltipText(), fontSize: 12 },
        },
        userTooltip,
      ),
      series: mergedSeries,
      ...userRest,
    }
  }

  /** ECharts chart + component modules, resolved lazily so SSR never loads canvas code. */
  private chartModules(charts: Record<string, unknown>, comps: Record<string, unknown>): unknown[] {
    return [charts['TreemapChart'], comps['TooltipComponent'], comps['TitleComponent']]
  }

  async ngAfterViewInit(): Promise<void> {
    if (typeof window === 'undefined' || !this.chartEl?.nativeElement) return
    const [{ use }, { CanvasRenderer }, charts, comps] = await Promise.all([
      import('echarts/core'),
      import('echarts/renderers'),
      import('echarts/charts'),
      import('echarts/components'),
    ])
    use([CanvasRenderer, ...(this.chartModules(charts, comps) as never[])])
    const { init } = await import('echarts/core')
    this.chart = init(this.chartEl.nativeElement)
    this.chart.setOption(this.getOption())
    const { onChartThemeChange } = await import('../use-chart-theme')
    this.unsubscribeTheme = onChartThemeChange(() => this.chart?.setOption(this.getOption()))
    if (typeof ResizeObserver !== 'undefined') {
      new ResizeObserver(() => this.chart?.resize()).observe(this.chartEl.nativeElement)
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (this.chart && Object.keys(changes).length) {
      this.chart.setOption(this.getOption())
    }
  }

  ngOnDestroy(): void {
    this.unsubscribeTheme?.()
    this.unsubscribeTheme = null
    try {
      this.chart?.dispose()
    } catch {
      /* already disposed */
    }
    this.chart = null
  }
}
