// packages/react/components/block-ui/BlockUi.tsx
import * as React from "react";
import { cn } from "@/lib/utils";
import { blockUiVariants } from "./block-ui.variants";
import { Spinner } from "@/components/ui/spinner";

export interface BlockUiProps extends React.HTMLAttributes<HTMLDivElement> {
  /** When true, the overlay is shown and the wrapped content is blocked. */
  blocking?: boolean;
  /** Plain-text or rich message shown under the icon. Ignored when a message
   *  render prop is supplied via children. */
  message?: React.ReactNode;
  opacity?: number;
  overlayColor?: string;
  blur?: boolean;
  showSpinner?: boolean;
  /** Custom icon node replacing the default Spinner (Vue #icon slot). */
  icon?: React.ReactNode;
  /** Custom message node replacing the `message` string (Vue #message slot). */
  messageSlot?: React.ReactNode;
}

const BlockUi = React.forwardRef<HTMLDivElement, BlockUiProps>(
  (
    {
      className,
      children,
      blocking = false,
      message = "Loading...",
      opacity = 0.6,
      overlayColor = "",
      blur = false,
      showSpinner = true,
      icon,
      messageSlot,
      ...props
    },
    ref,
  ) => {
    const overlayStyle: React.CSSProperties = React.useMemo(() => {
      const style: React.CSSProperties = { opacity };
      if (overlayColor) style.backgroundColor = overlayColor;
      return style;
    }, [opacity, overlayColor]);

    return (
      <div
        ref={ref}
        data-uipkge=""
        data-slot="block-ui"
        data-blocked={blocking ? "" : undefined}
        className={cn(blockUiVariants(), className)}
        {...props}
      >
        {/* Wrapped content — always non-interactive while blocked (not only when blur is on). */}
        <div
          className={cn(
            "block-ui-content",
            blocking && "pointer-events-none",
            blur && blocking && "blur-[2px] transition-[filter]",
          )}
          aria-hidden={blocking || undefined}
          {...(blocking ? { inert: true } : {})}
        >
          {children}
        </div>

        {/* Blocking overlay */}
        {blocking && (
          <div
            className="absolute inset-0 z-50 flex flex-col items-center justify-center gap-3"
            role="status"
            aria-live="polite"
            aria-busy="true"
          >
            {/* Background layer (opacity only affects this layer) */}
            <div
              className={cn(
                "absolute inset-0",
                !overlayColor && "bg-background",
              )}
              style={overlayStyle}
            />
            {/* Content layer (spinner + message stay fully opaque) */}
            {icon ?? (showSpinner && <Spinner size="lg" />)}
            {messageSlot ? (
              <div className="text-foreground text-sm font-medium">
                {messageSlot}
              </div>
            ) : (
              message && (
                <p className="text-foreground text-sm font-medium">{message}</p>
              )
            )}
          </div>
        )}
      </div>
    );
  },
);
BlockUi.displayName = "BlockUi";

export { BlockUi };

// packages/angular/components/block-ui/block-ui.component.ts
import { Component, Input, TemplateRef, booleanAttribute, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '@/lib/utils'
import { UiRenderTemplateDirective } from '@/ui/popper/popper'
import { UiSpinnerComponent } from '@/ui/spinner/spinner.component'
import { blockUiVariants } from './block-ui.variants'

/**
 * Angular port of UIPKGE BlockUi (React `BlockUi`). Wraps content; while `blocking` the
 * content is inert + aria-hidden (optionally blurred) and an overlay shows a Spinner (or the
 * `icon` template) and the `message` (or the `messageSlot` template). `opacity` /
 * `overlayColor` only affect the backdrop layer, so the spinner and message stay opaque.
 */
@Component({
  changeDetection: ChangeDetectionStrategy.Eager,
  selector: 'ui-block-ui, [ui-block-ui]',
  standalone: true,
  imports: [UiRenderTemplateDirective, UiSpinnerComponent],
  host: {
    '[attr.data-uipkge]': '""',
    '[attr.data-slot]': '"block-ui"',
    '[attr.data-blocked]': 'blocking ? "" : null',
    '[class]': 'hostClass',
  },
  template: `
    <div [class]="contentClass" [attr.aria-hidden]="blocking ? 'true' : null" [attr.inert]="blocking ? '' : null">
      <ng-content />
    </div>
    @if (blocking) {
      <div
        class="absolute inset-0 z-50 flex flex-col items-center justify-center gap-3"
        role="status"
        aria-live="polite"
        aria-busy="true"
      >
        <div [class]="backdropClass" [style.opacity]="opacity" [style.background-color]="overlayColor || null"></div>
        @if (icon) {
          <ng-container [uiRenderTemplate]="icon" />
        } @else if (showSpinner) {
          <ui-spinner size="lg" />
        }
        @if (messageSlot) {
          <div class="text-foreground text-sm font-medium"><ng-container [uiRenderTemplate]="messageSlot" /></div>
        } @else if (message) {
          <p class="text-foreground text-sm font-medium">{{ message }}</p>
        }
      </div>
    }
  `,
})
export class UiBlockUiComponent {
  /** When true, the overlay is shown and the wrapped content is blocked. */
  @Input({ transform: booleanAttribute }) blocking = false
  @Input() message = 'Loading...'
  @Input() opacity = 0.6
  @Input() overlayColor = ''
  @Input({ transform: booleanAttribute }) blur = false
  @Input({ transform: booleanAttribute }) showSpinner = true
  /** Custom icon template replacing the default Spinner (React `icon`). */
  @Input() icon?: TemplateRef<unknown> | null
  /** Custom message template replacing the `message` string (React `messageSlot`). */
  @Input() messageSlot?: TemplateRef<unknown> | null
  @Input('class') className?: string

  get hostClass(): string {
    return cn(blockUiVariants(), this.className)
  }

  get contentClass(): string {
    return cn(
      'block-ui-content',
      this.blocking && 'pointer-events-none',
      this.blur && this.blocking && 'blur-[2px] transition-[filter]',
    )
  }

  get backdropClass(): string {
    return cn('absolute inset-0', !this.overlayColor && 'bg-background')
  }
}

export { blockUiVariants }
