// packages/angular/components/charts/heikin-ashi-chart/heikin-ashi-chart.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  SimpleChanges,
  ViewChild,
  ChangeDetectionStrategy,
} from '@angular/core'
import type * as echarts from 'echarts/core'
import { cn } from '@/lib/utils'
import {
  getChartColors,
  getChartTextColor,
  getChartAxisColor,
  getChartSplitLineColor,
  getChartTooltipBg,
  getChartTooltipBorder,
  getChartTooltipText,
  mergeOptionBlock,
} from '../use-chart-theme'

/**
 * Angular port of the UIPKGE HeikinAshiChart — OHLC averaged candle-over-candle (pure ha()). Standalone, theme-aware. Same inputs as the Vue `HeikinAshiChart` (`data`, `zoom`, `height`, `option`).
 */
@Component({
  changeDetection: ChangeDetectionStrategy.Eager,
  selector: 'ui-heikin-ashi-chart, [ui-heikin-ashi-chart]',
  standalone: true,
  host: {
    '[attr.data-slot]': '"heikin-ashi-chart"',
    '[attr.data-uipkge]': '""',
    '[class]': 'hostClass',
    '[attr.role]': '"img"',
    '[attr.aria-label]': 'ariaLabel || "Chart"',
    '[attr.tabindex]': '0',
    '[style.height]': 'heightStyle',
  },
  template: `<div #chartEl class="size-full"></div>`,
})
export class UiHeikinAshiChartComponent implements AfterViewInit, OnChanges, OnDestroy {
  /** `{ date, open, high, low, close }` per candle. */
  @Input() data: { date: string; open: number; high: number; low: number; close: number }[] = []
  /** Show the data-zoom slider. Default false. */
  @Input() zoom = false
  @Input() height: number | string = 320
  @Input() option?: Record<string, unknown>
  /** Accessible name announced for the chart image. Defaults to "Chart". */
  @Input() ariaLabel?: string
  @Input('class') className?: string

  @ViewChild('chartEl', { static: false }) chartEl?: ElementRef<HTMLDivElement>

  private chart: echarts.ECharts | null = null
  private unsubscribeTheme: (() => void) | null = null

  get hostClass(): string {
    return cn('block focus-visible:ring-ring w-full focus-visible:ring-2 focus-visible:outline-none', this.className)
  }

  get heightStyle(): string {
    return /^\d+$/.test(String(this.height)) ? `${this.height}px` : String(this.height)
  }
  /** Heikin-Ashi averaging: each candle blends the previous one. Pure — unit-tested. */
  ha(): { date: string; open: number; high: number; low: number; close: number }[] {
    let prevOpen = this.data[0]?.open ?? 0
    let prevClose = this.data[0]?.close ?? 0
    return this.data.map((c) => {
      const haClose = (c.open + c.high + c.low + c.close) / 4
      const haOpen = (prevOpen + prevClose) / 2
      const haHigh = Math.max(c.high, haOpen, haClose)
      const haLow = Math.min(c.low, haOpen, haClose)
      prevOpen = haOpen
      prevClose = haClose
      return {
        date: c.date,
        open: +haOpen.toFixed(2),
        close: +haClose.toFixed(2),
        low: +haLow.toFixed(2),
        high: +haHigh.toFixed(2),
      }
    })
  }

  /** Build the merged ECharts option (pure — no DOM needed, unit-testable). */
  getOption(): Record<string, unknown> {
    const colors = getChartColors()
    const rows = this.ha()
    const series = [
      {
        type: 'candlestick',
        data: rows.map((c) => [c.open, c.close, c.low, c.high]),
        itemStyle: { color: colors[1], color0: colors[3], borderColor: colors[1], borderColor0: colors[3] },
      },
    ]
    const userOption: Record<string, any> = this.option ?? {}
    const {
      series: userSeries,
      xAxis: userXAxis,
      yAxis: userYAxis,
      grid: userGrid,
      tooltip: userTooltip,
      ...userRest
    } = userOption
    const mergedSeries = Array.isArray(userSeries) ? series.map((s, i) => ({ ...s, ...(userSeries[i] ?? {}) })) : series
    return {
      color: colors,
      grid: mergeOptionBlock(
        {
          left: 16,
          right: 16,
          top: 24,
          bottom: this.zoom ? 56 : 24,
          outerBoundsMode: 'same',
          outerBoundsContain: 'axisLabel',
        },
        userGrid,
      ),
      tooltip: mergeOptionBlock(
        {
          trigger: 'axis',
          axisPointer: { type: 'cross' },
          backgroundColor: getChartTooltipBg(),
          borderColor: getChartTooltipBorder(),
          textStyle: { color: getChartTooltipText(), fontSize: 12 },
        },
        userTooltip,
      ),
      xAxis: mergeOptionBlock(
        {
          type: 'category',
          data: rows.map((c) => c.date),
          scale: true,
          axisLine: { lineStyle: { color: getChartAxisColor() } },
          axisLabel: { color: getChartTextColor(), fontSize: 11 },
          axisTick: { show: false },
        },
        userXAxis,
      ),
      yAxis: mergeOptionBlock(
        {
          type: 'value',
          scale: true,
          splitLine: { lineStyle: { color: getChartSplitLineColor() } },
          axisLabel: { color: getChartTextColor(), fontSize: 11 },
        },
        userYAxis,
      ),
      dataZoom: this.zoom ? [{ type: 'inside' }, { type: 'slider' }] : undefined,
      series: mergedSeries,
      ...userRest,
    }
  }

  async ngAfterViewInit(): Promise<void> {
    if (typeof window === 'undefined' || !this.chartEl?.nativeElement) return
    const [{ use }, { CanvasRenderer }, { CandlestickChart: EChartsCandlestickChart }, comps] = await Promise.all([
      import('echarts/core'),
      import('echarts/renderers'),
      import('echarts/charts'),
      import('echarts/components'),
    ])
    use([CanvasRenderer, EChartsCandlestickChart, comps.GridComponent, comps.TooltipComponent, comps.DataZoomComponent])
    const { init } = await import('echarts/core')
    this.chart = init(this.chartEl.nativeElement)
    this.chart.setOption(this.getOption())
    const { onChartThemeChange } = await import('../use-chart-theme')
    this.unsubscribeTheme = onChartThemeChange(() => this.chart?.setOption(this.getOption()))
    if (typeof ResizeObserver !== 'undefined') {
      new ResizeObserver(() => this.chart?.resize()).observe(this.chartEl.nativeElement)
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (this.chart && (changes['data'] || changes['option'] || changes['zoom'])) {
      this.chart.setOption(this.getOption())
    }
  }

  ngOnDestroy(): void {
    this.unsubscribeTheme?.()
    this.unsubscribeTheme = null
    try {
      this.chart?.dispose()
    } catch {
      /* already disposed */
    }
    this.chart = null
  }
}

// packages/svelte/components/heikin-ashi-chart/HeikinAshiChart.svelte
<script lang="ts" module>
  import type { HTMLAttributes } from 'svelte/elements'

  export interface Candle {
    date: string
    open: number
    close: number
    low: number
    high: number
  }

  export interface HeikinAshiChartProps extends HTMLAttributes<HTMLDivElement> {
    data: Candle[]
    height?: number | string
    /** Show the bottom data-zoom slider. Default false. */
    zoom?: boolean
    option?: any
    /** Accessible name announced for the chart image. Defaults to "Chart". */
    ariaLabel?: string
  }
</script>

<script lang="ts">
  // @ts-ignore: echarts is a consumer dependency (see heikin-ashi-chart.registry.ts) and is not installed in this package.
  import { use, init } from 'echarts/core'
  // @ts-ignore: echarts is a consumer dependency (see heikin-ashi-chart.registry.ts) and is not installed in this package.
  import { CanvasRenderer } from 'echarts/renderers'
  // @ts-ignore: echarts is a consumer dependency (see heikin-ashi-chart.registry.ts) and is not installed in this package.
  import { CandlestickChart as EChartsCandlestickChart } from 'echarts/charts'
  // @ts-ignore: echarts is a consumer dependency (see heikin-ashi-chart.registry.ts) and is not installed in this package.
  import { GridComponent, TooltipComponent, DataZoomComponent } from 'echarts/components'
  import { cn } from '$lib/utils'
  import {
    mergeOptionBlock,
    resolveChartAxisColor,
    resolveChartColors,
    resolveChartSplitLineColor,
    resolveChartTextColor,
    resolveChartTooltipBg,
    resolveChartTooltipBorder,
    resolveChartTooltipText,
    watchTheme,
  } from './chart-theme'

  use([CanvasRenderer, EChartsCandlestickChart, GridComponent, TooltipComponent, DataZoomComponent])

  let {
    class: className,
    data,
    height = 320,
    zoom = false,
    option,
    ariaLabel,
    ...restProps
  }: HeikinAshiChartProps = $props()

  let themeKey = $state(0)
  $effect(() => watchTheme(() => (themeKey += 1)))

  const theme = $derived.by(() => {
    themeKey // re-resolve CSS tokens when the theme flips
    return {
      colors: resolveChartColors(),
      text: resolveChartTextColor(),
      axis: resolveChartAxisColor(),
      splitLine: resolveChartSplitLineColor(),
      tooltipBg: resolveChartTooltipBg(),
      tooltipBorder: resolveChartTooltipBorder(),
      tooltipText: resolveChartTooltipText(),
    }
  })

  // Heikin-Ashi: each candle averages the previous one, filtering market
  // noise so trends read as uninterrupted bull/bear runs.
  const ha = $derived.by(() => {
    let prevOpen = data[0]?.open ?? 0
    let prevClose = data[0]?.close ?? 0
    return data.map((c) => {
      const haClose = (c.open + c.high + c.low + c.close) / 4
      const haOpen = (prevOpen + prevClose) / 2
      const haHigh = Math.max(c.high, haOpen, haClose)
      const haLow = Math.min(c.low, haOpen, haClose)
      prevOpen = haOpen
      prevClose = haClose
      return {
        date: c.date,
        open: +haOpen.toFixed(2),
        close: +haClose.toFixed(2),
        low: +haLow.toFixed(2),
        high: +haHigh.toFixed(2),
      }
    })
  })

  const mergedOption = $derived.by(() => {
    const t = theme
    const candles = ha
    const series = [
      {
        type: 'candlestick',
        data: candles.map((c) => [c.open, c.close, c.low, c.high]),
        itemStyle: {
          color: t.colors[1],
          color0: t.colors[3],
          borderColor: t.colors[1],
          borderColor0: t.colors[3],
        },
      },
    ]
    const userOption: any = option ?? {}
    const {
      series: userSeries,
      xAxis: userXAxis,
      yAxis: userYAxis,
      grid: userGrid,
      tooltip: userTooltip,
      ...userRest
    } = userOption
    const mergedSeries = Array.isArray(userSeries)
      ? series.map((s, i) => ({ ...s, ...(userSeries[i] ?? {}) }))
      : series
    return {
      color: t.colors,
      grid: mergeOptionBlock(
        { left: 16, right: 16, top: 24, bottom: zoom ? 60 : 24, containLabel: true },
        userGrid,
      ),
      tooltip: mergeOptionBlock(
        {
          trigger: 'axis',
          axisPointer: { type: 'cross' },
          backgroundColor: t.tooltipBg,
          borderColor: t.tooltipBorder,
          textStyle: { color: t.tooltipText, fontSize: 12 },
        },
        userTooltip,
      ),
      xAxis: mergeOptionBlock(
        {
          type: 'category',
          data: candles.map((c) => c.date),
          axisLine: { lineStyle: { color: t.axis } },
          axisLabel: { color: t.text, fontSize: 11 },
          axisTick: { show: false },
        },
        userXAxis,
      ),
      yAxis: mergeOptionBlock(
        {
          type: 'value',
          scale: true,
          splitLine: { lineStyle: { color: t.splitLine } },
          axisLabel: { color: t.text, fontSize: 11 },
        },
        userYAxis,
      ),
      dataZoom: zoom ? [{ type: 'slider', bottom: 8, height: 18 }, { type: 'inside' }] : undefined,
      series: mergedSeries,
      ...userRest,
    }
  })

  const heightStyle = $derived(/^\d+$/.test(String(height)) ? `${height}px` : String(height))

  let viewport: HTMLDivElement | null = null
  let chart = $state<{ setOption: (option: unknown) => void } | null>(null)

  $effect(() => {
    if (!viewport) return
    const instance = init(viewport)
    chart = instance
    const ro = new ResizeObserver(() => instance.resize())
    ro.observe(viewport)
    return () => {
      ro.disconnect()
      instance.dispose()
      chart = null
    }
  })

  $effect(() => {
    chart?.setOption(mergedOption)
  })
</script>

<div
  data-uipkge
  data-slot="heikin-ashi-chart"
  role="img"
  tabindex="0"
  aria-label={ariaLabel || 'Heikin-Ashi chart'}
  {...restProps}
  style="height: {heightStyle}"
  class={cn('focus-visible:ring-ring w-full focus-visible:ring-2 focus-visible:outline-none', className)}
>
  <div bind:this={viewport} class="size-full"></div>
</div>
