// packages/vue/components/vertical-tabs/VerticalTabsContent.vue
<script setup lang="ts">
import { computed } from "vue";
import type { HTMLAttributes } from "vue";
import { TabsContent } from "reka-ui";
import { cn } from "@/lib/utils";

interface Props {
  class?: HTMLAttributes["class"];
  value: string;
  forceMount?: boolean;
}

const props = defineProps<Props>();

const delegated = computed(() => {
  const { class: _, ...rest } = props;
  return rest;
});
</script>

<template>
  <TabsContent
    v-slot="slotProps"
    data-uipkge
    data-slot="vertical-tabs-content"
    v-bind="delegated"
    :class="
      cn(
        'ring-offset-background focus-visible:ring-ring/50 flex-1 focus-visible:ring-2 focus-visible:outline-none',
        props.class,
      )
    "
    :force-mount="props.forceMount"
  >
    <slot v-bind="slotProps" />
  </TabsContent>
</template>

// packages/svelte/components/vertical-tabs/VerticalTabsContent.svelte
<script lang="ts" module>
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  export interface VerticalTabsContentProps extends HTMLAttributes<HTMLDivElement> {
    children?: Snippet
    value: string
    forceMount?: boolean
  }
</script>

<script lang="ts">
  import { cn } from '$lib/utils'
  import { getVerticalTabsContext, sanitizeId } from './VerticalTabs.svelte'

  let { children, value, forceMount = false, class: className, ...restProps }: VerticalTabsContentProps = $props()

  const ctx = getVerticalTabsContext('VerticalTabsContent')

  const active = $derived(ctx.getValue() === value)
  const triggerId = $derived(`${ctx.rootId}-trigger-${sanitizeId(value)}`)
  const contentId = $derived(`${ctx.rootId}-content-${sanitizeId(value)}`)
</script>

{#if forceMount || active}
  <div
    data-uipkge
    data-slot="vertical-tabs-content"
    data-state={active ? 'active' : 'inactive'}
    id={contentId}
    role="tabpanel"
    aria-labelledby={triggerId}
    tabindex="0"
    hidden={forceMount && !active ? true : undefined}
    class={cn(
      'ring-offset-background focus-visible:ring-ring/50 flex-1 focus-visible:ring-2 focus-visible:outline-none',
      className,
    )}
    {...restProps}
  >
    {@render children?.()}
  </div>
{/if}
