// packages/angular/components/loading-bar/loading-bar.component.ts
import {
  Component,
  DestroyRef,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
  ViewEncapsulation,
  booleanAttribute,
  inject,
  signal,
  type Signal,
  ChangeDetectionStrategy,
} from '@angular/core'
import { cn } from '@/lib/utils'

// Copied verbatim from the React loading-bar (injected there as an inline <style>). Unscoped
// (ViewEncapsulation.None) so the class matches the template's indeterminate bar.
const LOADING_BAR_MOTION_STYLES = `
@media (prefers-reduced-motion: no-preference) {
  .loading-bar-indeterminate {
    animation: loading-bar-slide 1.2s ease-in-out infinite;
  }
}
@keyframes loading-bar-slide {
  0% { left: -33%; }
  100% { left: 100%; }
}
`

/** Imperative API — same shape as React's `LoadingBarHandle`. */
export interface LoadingBarHandle {
  start: (from?: number) => void
  finish: () => void
  error: () => void
  fail: () => void
  inc: (amount?: number) => void
  set: (value: number) => void
}

/**
 * Angular port of UIPKGE LoadingBar (React `LoadingBar`). NProgress-style bar fixed to the
 * top / bottom of the viewport. Drive it with `value` / `valueChange`, or imperatively
 * (`start` trickles toward 95 on animation frames, `finish` fills to 100 then fades and
 * resets, `error` / `fail` tints destructive then fades). State is signal-backed so timers
 * and frames repaint in zoneless apps.
 */
@Component({
  changeDetection: ChangeDetectionStrategy.Eager,
  selector: 'ui-loading-bar, [ui-loading-bar]',
  standalone: true,
  encapsulation: ViewEncapsulation.None,
  styles: [LOADING_BAR_MOTION_STYLES],
  host: {
    '[attr.data-uipkge]': '""',
    '[attr.data-slot]': '"loading-bar"',
    '[attr.data-position]': 'position',
    '[attr.data-state]': 'isError ? "error" : indeterminate ? "indeterminate" : "determinate"',
    '[class]': 'hostClass',
    '[style.height.px]': 'height',
    '[attr.role]': '"progressbar"',
    '[attr.aria-valuemin]': '0',
    '[attr.aria-valuemax]': '100',
    '[attr.aria-valuenow]': 'indeterminate ? null : pct',
    '[attr.aria-busy]': 'visible && !isError ? "true" : null',
    '[attr.aria-hidden]': 'visible ? "false" : "true"',
    // `hidden` is an input (React prop), never the native attribute on the host.
    '[attr.hidden]': 'null',
  },
  template: `
    <div class="absolute inset-0 bg-transparent"></div>
    @if (indeterminate) {
      <div
        data-slot="loading-bar-indeterminate"
        class="loading-bar-indeterminate absolute inset-y-0 w-1/3"
        [style.background-color]="barColor"
      >
        @if (spinner) {
          <div
            data-slot="loading-bar-spinner"
            class="absolute top-1/2 right-0 size-3 translate-x-1/2 -translate-y-1/2 animate-spin rounded-full border-2 border-current border-t-transparent"
            [style.color]="barColor"
          ></div>
        }
      </div>
    } @else {
      <div
        data-slot="loading-bar-fill"
        class="absolute inset-y-0 left-0 transition-[width] duration-200 ease-out"
        [style.width.%]="pct"
        [style.background-color]="barColor"
      >
        @if (spinner) {
          <div
            data-slot="loading-bar-spinner"
            class="absolute top-1/2 right-0 size-3 translate-x-1/2 -translate-y-1/2 animate-spin rounded-full border-2 border-current border-t-transparent"
            [style.color]="barColor"
          ></div>
        }
      </div>
    }
  `,
})
export class UiLoadingBarComponent implements OnChanges, LoadingBarHandle {
  /** 0–100 progress value. Use with value / valueChange or drive it imperatively. */
  @Input() value = 0
  /** Bar color. Accepts any CSS color value. */
  @Input() color = ''
  /** Bar height in px. */
  @Input() height = 3
  /** Indeterminate sliding animation (ignores value). */
  @Input({ transform: booleanAttribute }) indeterminate = false
  /** Anchor the bar to the top or bottom of the viewport. */
  @Input() position: 'top' | 'bottom' = 'top'
  /** Show a spinner at the trailing edge of the bar. */
  @Input({ transform: booleanAttribute }) spinner = false
  /** Error state tints the bar (React `error` prop; the `error()` method is the imperative form). */
  @Input({ alias: 'error', transform: booleanAttribute }) errorState = false
  /** Hide the bar entirely (e.g. when finished). */
  @Input({ transform: booleanAttribute }) hidden = false
  @Input('class') className?: string
  /** Fired with the new value on every internal update. */
  @Output() readonly valueChange = new EventEmitter<number>()
  /** Fired when progress reaches 100 (finish / fail). */
  @Output('finish') readonly finished = new EventEmitter<void>()

  readonly internal = signal(0)
  /** Imperative fail() tints the bar without requiring the error input. */
  private readonly internalError = signal(false)
  /** After finish / fail, fade out then reset. */
  private readonly fading = signal(false)
  private raf: number | null = null
  private hideTimer: ReturnType<typeof setTimeout> | null = null
  /** Bumped on start / finish / fail so in-flight trickle frames abort. */
  private generation = 0

  constructor() {
    inject(DestroyRef).onDestroy(() => this.clearTimers())
  }

  ngOnChanges(changes: SimpleChanges): void {
    // Keep internal in sync when the controlled value input changes.
    if (changes['value']) this.internal.set(this.value)
  }

  get pct(): number {
    return Math.min(100, Math.max(0, this.internal()))
  }

  get isError(): boolean {
    return this.errorState || this.internalError()
  }

  get barColor(): string {
    return this.color || (this.isError ? 'var(--destructive)' : 'var(--primary)')
  }

  get visible(): boolean {
    return !this.hidden && !this.fading() && (this.indeterminate || this.internal() > 0)
  }

  get hostClass(): string {
    return cn(
      'block pointer-events-none fixed left-0 z-[9999] w-full transition-opacity duration-300',
      this.position === 'top' ? 'top-0' : 'bottom-0',
      this.visible ? 'opacity-100' : 'opacity-0',
      this.className,
    )
  }

  private clearTimers(): void {
    if (this.raf !== null) {
      cancelAnimationFrame(this.raf)
      this.raf = null
    }
    if (this.hideTimer) {
      clearTimeout(this.hideTimer)
      this.hideTimer = null
    }
  }

  private emit(v: number): void {
    this.valueChange.emit(v)
  }

  set(v: number): void {
    this.internal.set(v)
    this.emit(v)
  }

  /** Slowly creep the bar toward a soft ceiling so progress feels alive. */
  private trickle(gen: number): void {
    if (this.raf !== null) cancelAnimationFrame(this.raf)
    const step = () => {
      if (gen !== this.generation) return
      const prev = this.internal()
      if (prev >= 95) return
      const next = Math.min(95, prev + (95 - prev) * 0.04 + 0.15)
      this.internal.set(next)
      this.emit(next)
      if (next < 95 && gen === this.generation) this.raf = requestAnimationFrame(step)
    }
    this.raf = requestAnimationFrame(step)
  }

  start(from = 20): void {
    this.clearTimers()
    this.generation += 1
    const gen = this.generation
    this.internalError.set(false)
    this.fading.set(false)
    this.set(from)
    this.trickle(gen)
  }

  inc(amount = 10): void {
    const next = Math.min(99, this.internal() + amount)
    this.internal.set(next)
    this.emit(next)
  }

  finish(): void {
    this.clearTimers()
    this.generation += 1
    this.internalError.set(false)
    this.set(100)
    this.finished.emit()
    // Hold full bar briefly, then fade + reset so the next start() is clean.
    this.hideTimer = setTimeout(() => {
      this.fading.set(true)
      this.hideTimer = setTimeout(() => {
        this.internal.set(0)
        this.emit(0)
        this.fading.set(false)
        this.hideTimer = null
      }, 300)
    }, 200)
  }

  fail(): void {
    this.clearTimers()
    this.generation += 1
    this.internalError.set(true)
    this.internal.set(100)
    this.emit(100)
    this.finished.emit()
    this.hideTimer = setTimeout(() => {
      this.fading.set(true)
      this.hideTimer = setTimeout(() => {
        this.internal.set(0)
        this.internalError.set(false)
        this.emit(0)
        this.fading.set(false)
        this.hideTimer = null
      }, 300)
    }, 400)
  }

  error(): void {
    this.fail()
  }
}

export interface UseLoadingBar {
  /** Pass the bar instance (e.g. from a `@ViewChild` setter). */
  setRef: (bar: UiLoadingBarComponent | null | undefined) => void
  loading: Signal<boolean>
  isError: Signal<boolean>
  start: (from?: number) => void
  finish: () => void
  error: () => void
  inc: (amount?: number) => void
  set: (value: number) => void
}

/**
 * Angular counterpart of React's `useLoadingBar` hook: drives a `<ui-loading-bar>` through
 * `setRef` and tracks `loading` / `isError` as signals.
 *
 *   bar = useLoadingBar()
 *   @ViewChild(UiLoadingBarComponent) set barRef(b: UiLoadingBarComponent) { this.bar.setRef(b) }
 *   this.bar.start(); await fetch(...); this.bar.finish()
 */
export function useLoadingBar(initial?: UiLoadingBarComponent | null): UseLoadingBar {
  let handle: UiLoadingBarComponent | null = initial ?? null
  const loading = signal(false)
  const isError = signal(false)
  return {
    setRef: (bar) => {
      handle = bar ?? null
    },
    loading: loading.asReadonly(),
    isError: isError.asReadonly(),
    start(from = 20) {
      isError.set(false)
      loading.set(true)
      handle?.start(from)
    },
    finish() {
      loading.set(false)
      handle?.finish()
    },
    error() {
      isError.set(true)
      loading.set(false)
      handle?.error()
    },
    inc(amount = 10) {
      handle?.inc(amount)
    },
    set(value: number) {
      handle?.set(value)
    },
  }
}

// packages/react/components/loading-bar/LoadingBar.tsx
"use client";

import * as React from "react";
import { cn } from "@/lib/utils";

export interface LoadingBarHandle {
  start: (from?: number) => void;
  finish: () => void;
  error: () => void;
  fail: () => void;
  inc: (amount?: number) => void;
  set: (value: number) => void;
}

export interface LoadingBarProps extends Omit<
  React.HTMLAttributes<HTMLDivElement>,
  "onChange"
> {
  /** 0–100 progress value. Use with value/onChange or drive via the hook. */
  value?: number;
  /** Bar color. Accepts any CSS color value. */
  color?: string;
  /** Bar height in px. */
  height?: number;
  /** Indeterminate sliding animation (ignores value). */
  indeterminate?: boolean;
  /** Anchor the bar to the top or bottom of the viewport. */
  position?: "top" | "bottom";
  /** Show a spinner at the trailing edge of the bar. */
  spinner?: boolean;
  /** Error state tints the bar. */
  error?: boolean;
  /** Hide the bar entirely (e.g. when finished). */
  hidden?: boolean;
  /** Fired with the new value on every internal update (v-model equivalent). */
  onValueChange?: (value: number) => void;
  /** Fired when progress reaches 100. */
  onFinish?: () => void;
}

const LoadingBar = React.forwardRef<LoadingBarHandle, LoadingBarProps>(
  (
    {
      value = 0,
      color = "",
      height = 3,
      indeterminate = false,
      position = "top",
      spinner = false,
      error = false,
      hidden = false,
      className,
      onValueChange,
      onFinish,
      ...props
    },
    ref,
  ) => {
    const [internal, setInternal] = React.useState(value);
    /** Imperative fail() tints the bar without requiring the error prop. */
    const [internalError, setInternalError] = React.useState(false);
    /** After finish/fail, fade out then reset. */
    const [fading, setFading] = React.useState(false);
    const rafRef = React.useRef<number | null>(null);
    const hideTimerRef = React.useRef<ReturnType<typeof setTimeout> | null>(
      null,
    );
    /** Bumped on start/finish/fail so in-flight trickle frames abort. */
    const generationRef = React.useRef(0);
    const onValueChangeRef = React.useRef(onValueChange);
    const onFinishRef = React.useRef(onFinish);
    onValueChangeRef.current = onValueChange;
    onFinishRef.current = onFinish;

    // Keep internal in sync when the controlled value prop changes.
    React.useEffect(() => {
      setInternal(value);
    }, [value]);

    const clearTimers = React.useCallback(() => {
      if (rafRef.current) {
        cancelAnimationFrame(rafRef.current);
        rafRef.current = null;
      }
      if (hideTimerRef.current) {
        clearTimeout(hideTimerRef.current);
        hideTimerRef.current = null;
      }
    }, []);

    const set = React.useCallback((v: number) => {
      setInternal(v);
      onValueChangeRef.current?.(v);
    }, []);

    /** Slowly creep the bar toward a soft ceiling so progress feels alive. */
    const trickle = React.useCallback((gen: number) => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
      const step = () => {
        if (gen !== generationRef.current) return;
        setInternal((prev) => {
          if (gen !== generationRef.current || prev >= 95) return prev;
          const next = Math.min(95, prev + (95 - prev) * 0.04 + 0.15);
          onValueChangeRef.current?.(next);
          if (next < 95 && gen === generationRef.current) {
            rafRef.current = requestAnimationFrame(step);
          }
          return next;
        });
      };
      rafRef.current = requestAnimationFrame(step);
    }, []);

    const start = React.useCallback(
      (from = 20) => {
        clearTimers();
        generationRef.current += 1;
        const gen = generationRef.current;
        setInternalError(false);
        setFading(false);
        set(from);
        trickle(gen);
      },
      [set, trickle, clearTimers],
    );

    const inc = React.useCallback((amount = 10) => {
      setInternal((prev) => {
        const next = Math.min(99, prev + amount);
        onValueChangeRef.current?.(next);
        return next;
      });
    }, []);

    const finish = React.useCallback(() => {
      clearTimers();
      generationRef.current += 1;
      setInternalError(false);
      set(100);
      onFinishRef.current?.();
      // Hold full bar briefly, then fade + reset so the next start() is clean.
      hideTimerRef.current = setTimeout(() => {
        setFading(true);
        hideTimerRef.current = setTimeout(() => {
          setInternal(0);
          onValueChangeRef.current?.(0);
          setFading(false);
          hideTimerRef.current = null;
        }, 300);
      }, 200);
    }, [set, clearTimers]);

    const fail = React.useCallback(() => {
      clearTimers();
      generationRef.current += 1;
      setInternalError(true);
      setInternal(100);
      onValueChangeRef.current?.(100);
      onFinishRef.current?.();
      hideTimerRef.current = setTimeout(() => {
        setFading(true);
        hideTimerRef.current = setTimeout(() => {
          setInternal(0);
          setInternalError(false);
          onValueChangeRef.current?.(0);
          setFading(false);
          hideTimerRef.current = null;
        }, 300);
      }, 400);
    }, [clearTimers]);

    React.useEffect(() => {
      return () => {
        clearTimers();
      };
    }, [clearTimers]);

    React.useImperativeHandle(
      ref,
      () => ({ start, finish, error: fail, fail, inc, set }),
      [start, finish, fail, inc, set],
    );

    const pct = Math.min(100, Math.max(0, internal));
    const isError = error || internalError;
    const barColor =
      color || (isError ? "var(--destructive)" : "var(--primary)");
    const visible = !hidden && !fading && (indeterminate || internal > 0);

    return (
      <div
        data-uipkge=""
        data-slot="loading-bar"
        data-position={position}
        data-state={
          isError ? "error" : indeterminate ? "indeterminate" : "determinate"
        }
        className={cn(
          "pointer-events-none fixed left-0 z-[9999] w-full transition-opacity duration-300",
          position === "top" ? "top-0" : "bottom-0",
          visible ? "opacity-100" : "opacity-0",
          className,
        )}
        style={{ height: `${height}px`, ...(props.style ?? {}) }}
        role="progressbar"
        aria-valuemin={0}
        aria-valuemax={100}
        aria-valuenow={indeterminate ? undefined : pct}
        aria-busy={visible && !isError ? true : undefined}
        aria-hidden={!visible}
        {...props}
      >
        {/* Track */}
        <div className="absolute inset-0 bg-transparent" />

        {indeterminate ? (
          // Indeterminate sliding bar
          <div
            data-slot="loading-bar-indeterminate"
            className="loading-bar-indeterminate absolute inset-y-0 w-1/3"
            style={{ backgroundColor: barColor }}
          >
            {spinner && (
              <div
                data-slot="loading-bar-spinner"
                className="absolute top-1/2 right-0 size-3 translate-x-1/2 -translate-y-1/2 animate-spin rounded-full border-2 border-current border-t-transparent"
                style={{ color: barColor }}
              />
            )}
          </div>
        ) : (
          // Determinate bar
          <div
            data-slot="loading-bar-fill"
            className="absolute inset-y-0 left-0 transition-[width] duration-200 ease-out"
            style={{ width: `${pct}%`, backgroundColor: barColor }}
          >
            {spinner && (
              <div
                data-slot="loading-bar-spinner"
                className="absolute top-1/2 right-0 size-3 translate-x-1/2 -translate-y-1/2 animate-spin rounded-full border-2 border-current border-t-transparent"
                style={{ color: barColor }}
              />
            )}
          </div>
        )}

        <style>{`
@media (prefers-reduced-motion: no-preference) {
  .loading-bar-indeterminate {
    animation: loading-bar-slide 1.2s ease-in-out infinite;
  }
}
@keyframes loading-bar-slide {
  0% { left: -33%; }
  100% { left: 100%; }
}
`}</style>
      </div>
    );
  },
);
LoadingBar.displayName = "LoadingBar";

export { LoadingBar };
