// packages/angular/components/lazy-image/lazy-image.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  SimpleChanges,
  TemplateRef,
  ViewChild,
  booleanAttribute,
  signal,
  ChangeDetectionStrategy,
} from '@angular/core'
import { cn } from '@/lib/utils'
import { UiSkeletonComponent } from '@/ui/skeleton/skeleton.component'
import { UiRenderTemplateDirective } from '@/ui/popper/popper'

export type LazyImagePlaceholder = 'skeleton' | 'none'
export type LazyImageState = 'idle' | 'loading' | 'loaded' | 'error'

/**
 * Angular port of UIPKGE LazyImage (React `Img`). Lazy-loaded image with aspect-ratio
 * reservation, Skeleton placeholder, fade-in and error fallback. The <img> mounts once the host
 * comes within 200px of the viewport (IntersectionObserver; renders immediately without IO or
 * with `eager`). React's `fallbackContent` node is a TemplateRef input.
 */
@Component({
  changeDetection: ChangeDetectionStrategy.Eager,
  selector: 'ui-lazy-image, [ui-lazy-image]',
  standalone: true,
  imports: [UiSkeletonComponent, UiRenderTemplateDirective],
  host: {
    '[attr.data-slot]': '"lazy-image"',
    '[attr.data-uipkge]': '""',
    '[style.aspect-ratio]': 'aspectRatioStyle',
    '[style.width]': 'widthStyle',
    '[style.height]': 'heightStyle',
    '[class]': 'hostClass',
  },
  template: `<ng-container #anchor />
    @if (placeholder === 'skeleton' && state() !== 'loaded' && state() !== 'error') {
      <div ui-skeleton class="absolute inset-0 size-full rounded-none"></div>
    }
    @if (visible() && state() !== 'error') {
      <img
        [src]="src"
        [attr.srcset]="srcSet ?? null"
        [attr.sizes]="sizes ?? null"
        [alt]="alt"
        [attr.loading]="eager ? 'eager' : 'lazy'"
        [attr.decoding]="eager ? 'sync' : 'async'"
        [class]="imgClassMerged"
        (load)="onLoad($event)"
        (error)="onError($event)"
      />
    }
    @if (state() === 'error') {
      @if (fallbackContent) {
        <ng-container [uiRenderTemplate]="fallbackContent" />
      } @else if (fallback) {
        <img [src]="fallback" [alt]="alt" [class]="fallbackClass" />
      } @else {
        <div
          role="img"
          class="text-muted-foreground absolute inset-0 flex items-center justify-center text-xs"
          aria-label="Image failed to load"
        >
          <span aria-hidden="true">Image unavailable</span>
        </div>
      }
    }`,
})
export class UiLazyImageComponent implements OnChanges, AfterViewInit, OnDestroy {
  @Input() src = ''
  @Input() srcSet?: string
  @Input() sizes?: string
  @Input() alt = ''
  @Input() aspectRatio?: string | number
  @Input() width?: string | number
  @Input() height?: string | number
  @Input() placeholder: LazyImagePlaceholder = 'skeleton'
  @Input({ transform: booleanAttribute }) cover = true
  @Input({ transform: booleanAttribute }) eager = false
  @Input() fallback?: string
  @Input({ transform: booleanAttribute }) transition = true
  @Input('class') className?: string
  @Input() imgClassName?: string
  /** Overrides the default error fallback (React `fallbackContent`). */
  @Input() fallbackContent?: TemplateRef<unknown>

  /** React `onLoad` / `onError` (img load/error events don't bubble, so no native collision). */
  @Output() load = new EventEmitter<Event>()
  @Output() error = new EventEmitter<Event>()

  /** Comment node inside the host; its parent is the host element (no ElementRef injection needed). */
  @ViewChild('anchor', { read: ElementRef }) private anchor?: ElementRef<Comment>

  readonly state = signal<LazyImageState>('idle')
  readonly visible = signal(false)
  private observer?: IntersectionObserver
  private viewReady = false

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['src'] || changes['eager']) {
      this.state.set('idle')
      if (this.viewReady) this.observe()
      else if (this.eager) this.show()
    }
  }

  ngAfterViewInit(): void {
    this.viewReady = true
    this.observe()
  }

  ngOnDestroy(): void {
    this.observer?.disconnect()
  }

  /** Reset + (re)observe, like React's [src, eager] effect. */
  private observe(): void {
    this.observer?.disconnect()
    this.observer = undefined
    if (this.eager) return this.show()
    this.visible.set(false)
    const host = this.anchor?.nativeElement.parentElement
    if (typeof IntersectionObserver === 'undefined' || !host) return this.show()
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries.some((e) => e.isIntersecting)) {
          observer.disconnect()
          this.show()
        }
      },
      { rootMargin: '200px' },
    )
    this.observer = observer
    observer.observe(host)
  }

  private show(): void {
    this.visible.set(true)
    if (this.state() === 'idle') this.state.set('loading')
  }

  get hostClass(): string {
    return cn('block bg-muted relative overflow-hidden', this.className)
  }

  get imgClassMerged(): string {
    return cn(
      'block size-full',
      this.cover ? 'object-cover' : 'object-contain',
      this.transition && 'transition-opacity duration-300',
      this.state() === 'loaded' ? 'opacity-100' : 'opacity-0',
      this.imgClassName,
    )
  }

  get fallbackClass(): string {
    return cn('block size-full', this.cover ? 'object-cover' : 'object-contain', this.imgClassName)
  }

  get aspectRatioStyle(): string | null {
    return this.aspectRatio === undefined ? null : String(this.aspectRatio)
  }

  get widthStyle(): string | null {
    if (this.width === undefined) return null
    return typeof this.width === 'number' ? `${this.width}px` : this.width
  }

  get heightStyle(): string | null {
    if (this.height === undefined) return null
    return typeof this.height === 'number' ? `${this.height}px` : this.height
  }

  onLoad(e: Event): void {
    this.state.set('loaded')
    this.load.emit(e)
  }

  onError(e: Event): void {
    this.state.set('error')
    this.error.emit(e)
  }
}

// packages/lit/src/components/lazy-image/lazy-image.ts
import { LitElement, css, html, isServer, nothing } from 'lit'
import { cn } from '../../lib/utils'
import { tailwind } from '../../lib/styles'
import { ThemeController } from '../../lib/theme'

export type ImagePlaceholder = 'skeleton' | 'none'

const trueByDefault = {
  fromAttribute: (v: string | null) => v !== 'false' && v !== null,
  toAttribute: (v: boolean) => (v ? '' : 'false'),
}

/**
 * <uip-lazy-image> — progressive image loader with skeleton placeholder and fallback.
 */
export class UipLazyImage extends LitElement {
  static styles = [
    tailwind,
    css`
      :host {
        display: block;
        overflow: hidden;
        position: relative;
      }
    `,
  ]

  static properties = {
    src: { reflect: true },
    srcSet: { attribute: 'srcset', reflect: true },
    sizes: { reflect: true },
    alt: { reflect: true },
    aspectRatio: { attribute: 'aspect-ratio', reflect: true },
    width: { reflect: true },
    height: { reflect: true },
    placeholder: { reflect: true },
    cover: { converter: trueByDefault, reflect: true },
    eager: { type: Boolean, reflect: true },
    fallback: { reflect: true },
    transition: { converter: trueByDefault, reflect: true },
    state: { state: true },
    visible: { state: true },
  }

  src = ''
  srcSet?: string
  sizes?: string
  alt = ''
  aspectRatio?: string | number
  width?: string | number
  height?: string | number
  placeholder: ImagePlaceholder = 'skeleton'
  cover = true
  eager = false
  fallback?: string
  transition = true

  private state: 'idle' | 'loading' | 'loaded' | 'error' = 'idle'
  private visible = false
  private observer?: IntersectionObserver

  constructor() {
    super()
    new ThemeController(this)
  }

  connectedCallback() {
    super.connectedCallback()
    this.setAttribute('data-uipkge', '')
    this.setAttribute('data-slot', 'lazy-image')
    this.setupObserver()
  }

  disconnectedCallback() {
    super.disconnectedCallback()
    if (this.observer) {
      this.observer.disconnect()
      this.observer = undefined
    }
  }

  protected updated(changedProps: Map<string, unknown>) {
    super.updated(changedProps)
    if (changedProps.has('src') || changedProps.has('eager')) {
      this.state = 'idle'
      this.setupObserver()
    }
    if (this.visible && this.state === 'idle') {
      this.state = 'loading'
    }
  }

  private setupObserver() {
    if (isServer) {
      this.visible = true
      return
    }

    if (this.eager) {
      this.visible = true
      return
    }

    this.visible = false

    if (typeof IntersectionObserver === 'undefined') {
      this.visible = true
      return
    }

    if (this.observer) {
      this.observer.disconnect()
    }

    this.observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            this.visible = true
            this.observer?.disconnect()
            this.observer = undefined
            break
          }
        }
      },
      { rootMargin: '200px' },
    )
    this.observer.observe(this)
  }

  private onImgLoad(e: Event) {
    this.state = 'loaded'
    this.dispatchEvent(new CustomEvent('load', { bubbles: true, composed: true }))
  }

  private onImgError(e: Event) {
    this.state = 'error'
    this.dispatchEvent(new CustomEvent('error', { bubbles: true, composed: true }))
  }

  render() {
    const styleParts: string[] = []
    if (this.aspectRatio !== undefined) {
      const ar = typeof this.aspectRatio === 'number' ? String(this.aspectRatio) : this.aspectRatio
      styleParts.push(`aspect-ratio: ${ar};`)
    }
    if (this.width !== undefined) {
      const w = typeof this.width === 'number' ? `${this.width}px` : this.width
      styleParts.push(`width: ${w};`)
    }
    if (this.height !== undefined) {
      const h = typeof this.height === 'number' ? `${this.height}px` : this.height
      styleParts.push(`height: ${h};`)
    }
    const containerStyle = styleParts.join(' ')

    return html`
      <div
        part="base"
        data-slot="lazy-image"
        class="bg-muted relative size-full overflow-hidden"
        style=${containerStyle || nothing}
      >
        ${this.placeholder === 'skeleton' && this.state !== 'loaded' && this.state !== 'error'
          ? html`<uip-skeleton class="absolute inset-0 size-full rounded-none"></uip-skeleton>`
          : nothing}
        ${this.visible && this.state !== 'error'
          ? html`
              <img
                src=${this.src}
                srcset=${this.srcSet ?? nothing}
                sizes=${this.sizes ?? nothing}
                alt=${this.alt}
                loading=${this.eager ? 'eager' : 'lazy'}
                decoding=${this.eager ? 'sync' : 'async'}
                class=${cn(
                  'block size-full',
                  this.cover ? 'object-cover' : 'object-contain',
                  this.transition && 'transition-opacity duration-300',
                  this.state === 'loaded' ? 'opacity-100' : 'opacity-0',
                )}
                @load=${this.onImgLoad}
                @error=${this.onImgError}
              />
            `
          : nothing}
        ${this.state === 'error'
          ? html`
              <slot name="fallback">
                ${this.fallback
                  ? html`
                      <img
                        src=${this.fallback}
                        alt=${this.alt}
                        class=${cn('block size-full', this.cover ? 'object-cover' : 'object-contain')}
                      />
                    `
                  : html`
                      <div
                        role="img"
                        class="text-muted-foreground absolute inset-0 flex items-center justify-center text-xs"
                        aria-label="Image failed to load"
                      >
                        <span aria-hidden="true">Image unavailable</span>
                      </div>
                    `}
              </slot>
            `
          : nothing}
      </div>
    `
  }
}

customElements.get('uip-lazy-image') || customElements.define('uip-lazy-image', UipLazyImage)

declare global {
  interface HTMLElementTagNameMap {
    'uip-lazy-image': UipLazyImage
  }
}
