// packages/react/components/button/Button.tsx
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cn } from "@/lib/utils";
import { buttonVariants, type ButtonVariants } from "./button.variants";

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>, ButtonVariants {
  /** Render the child element as the button (merging props/styles) instead of
   *  emitting a <button> — the React equivalent of reka-ui's as-child. Use it
   *  to give a Next.js <Link> or <a> full button styling. */
  asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  (
    { className, variant, size, asChild = false, type = "button", ...props },
    ref,
  ) => {
    const Comp = asChild ? Slot : "button";
    return (
      <Comp
        data-uipkge=""
        data-slot="button"
        data-variant={variant ?? undefined}
        data-size={size ?? undefined}
        className={cn(buttonVariants({ variant, size }), className)}
        // Default type="button" avoids accidental form submits. asChild leaves
        // type to the child (e.g. <a> / Next.js Link) and must not receive it.
        {...(asChild ? {} : { type })}
        ref={ref}
        {...props}
      />
    );
  },
);
Button.displayName = "Button";

export { Button };

// packages/svelte/components/button/Button.svelte
<script lang="ts" module>
  import type { Snippet } from 'svelte'
  import type { HTMLButtonAttributes } from 'svelte/elements'
  import type { ButtonVariants } from './button.variants'

  export interface ButtonProps extends HTMLButtonAttributes {
    variant?: ButtonVariants['variant']
    size?: ButtonVariants['size']
    /** Render your own element with the button's props and styles instead of
     *  emitting a <button> — the Svelte counterpart of React's `asChild`. Use it
     *  to give an <a> full button styling: spread `props` onto your element. */
    child?: Snippet<[{ props: Record<string, unknown> }]>
    /** The rendered <button>, via `bind:ref`. Stays null in `child` mode — use
     *  `bind:this` on your own element there. */
    ref?: HTMLButtonElement | null
  }
</script>

<script lang="ts">
  import { cn } from '$lib/utils'
  import { buttonVariants } from './button.variants'

  let {
    class: className,
    variant = 'default',
    size = 'default',
    type = 'button',
    child,
    children,
    ref = $bindable(null),
    ...restProps
  }: ButtonProps = $props()

  const mergedProps = $derived({
    'data-uipkge': '',
    'data-slot': 'button',
    'data-variant': variant,
    'data-size': size,
    class: cn(buttonVariants({ variant, size }), className),
    ...restProps,
  })
</script>

{#if child}
  <!-- Default type="button" avoids accidental form submits. `child` leaves type
       to the consumer's element (e.g. <a>) and must not receive it. -->
  {@render child({ props: mergedProps })}
{:else}
  <button bind:this={ref} {type} {...mergedProps}>{@render children?.()}</button>
{/if}
