// packages/react/components/data-table/DataTablePagination.tsx
'use client'

import type { Table } from '@tanstack/react-table'
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

export interface DataTablePaginationProps {
  table: Table<any>
  totalRows: number
  isServerSide: boolean
  borderless?: boolean
}

export function DataTablePagination({ table, totalRows, isServerSide, borderless = false }: DataTablePaginationProps) {
  const selected = table.getFilteredSelectedRowModel().rows.length
  const total = isServerSide ? totalRows : table.getFilteredRowModel().rows.length

  return (
    <div
      className={[
        'flex flex-col gap-3 py-3 sm:flex-row sm:items-center sm:justify-between',
        borderless ? '' : 'border-t px-4',
      ].join(' ')}
    >
      <div className="text-muted-foreground text-sm tabular-nums">
        <span className="text-foreground font-medium">{selected}</span> of {total} row(s) selected
      </div>
      <div className="flex flex-wrap items-center gap-4 sm:gap-6">
        <div className="flex items-center gap-2">
          <p className="text-sm font-medium whitespace-nowrap">Rows per page</p>
          <Select
            value={`${table.getState().pagination.pageSize}`}
            onValueChange={(value) => {
              table.setPageSize(Number(value))
              table.setPageIndex(0)
            }}
          >
            <SelectTrigger className="h-8 w-[4.5rem]">
              <SelectValue placeholder={`${table.getState().pagination.pageSize}`} />
            </SelectTrigger>
            <SelectContent side="top">
              {[10, 20, 30, 40, 50].map((pageSize) => (
                <SelectItem key={pageSize} value={`${pageSize}`}>
                  {pageSize}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="text-sm font-medium whitespace-nowrap tabular-nums">
          Page {table.getState().pagination.pageIndex + 1} of {Math.max(table.getPageCount(), 1)}
        </div>
        <div className="flex items-center gap-1">
          <Button
            variant="outline"
            size="icon"
            className="hidden size-8 lg:flex"
            disabled={!table.getCanPreviousPage()}
            onClick={() => table.setPageIndex(0)}
          >
            <ChevronsLeft className="size-4" aria-hidden="true" />
            <span className="sr-only">First page</span>
          </Button>
          <Button
            variant="outline"
            size="icon"
            className="size-8"
            disabled={!table.getCanPreviousPage()}
            onClick={() => table.previousPage()}
          >
            <ChevronLeft className="size-4" aria-hidden="true" />
            <span className="sr-only">Previous page</span>
          </Button>
          <Button
            variant="outline"
            size="icon"
            className="size-8"
            disabled={!table.getCanNextPage()}
            onClick={() => table.nextPage()}
          >
            <ChevronRight className="size-4" aria-hidden="true" />
            <span className="sr-only">Next page</span>
          </Button>
          <Button
            variant="outline"
            size="icon"
            className="hidden size-8 lg:flex"
            disabled={!table.getCanNextPage()}
            onClick={() => table.setPageIndex(table.getPageCount() - 1)}
          >
            <ChevronsRight className="size-4" aria-hidden="true" />
            <span className="sr-only">Last page</span>
          </Button>
        </div>
      </div>
    </div>
  )
}

// packages/vue/components/data-table/DataTablePagination.vue
<script setup lang="ts">
import type { Table } from "@tanstack/vue-table";

import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
} from "lucide-vue-next";

withDefaults(
  defineProps<{
    table: Table<any>;
    totalRows: number;
    isServerSide: boolean;
    borderless?: boolean;
  }>(),
  { borderless: false },
);
</script>

<template>
  <div
    :class="[
      'flex flex-col gap-3 py-3 sm:flex-row sm:items-center sm:justify-between',
      borderless ? '' : 'border-t px-4',
    ]"
  >
    <div class="text-muted-foreground text-sm tabular-nums">
      <span class="text-foreground font-medium">{{
        table.getFilteredSelectedRowModel().rows.length
      }}</span>
      of
      {{ isServerSide ? totalRows : table.getFilteredRowModel().rows.length }}
      row(s) selected
    </div>
    <div class="flex flex-wrap items-center gap-4 sm:gap-6">
      <div class="flex items-center gap-2">
        <p class="text-sm font-medium whitespace-nowrap">Rows per page</p>
        <Select
          :model-value="`${table.getState().pagination.pageSize}`"
          @update:model-value="
            (value) => {
              table.setPageSize(Number(value));
              table.setPageIndex(0);
            }
          "
        >
          <SelectTrigger class="h-8 w-[4.5rem]">
            <SelectValue
              :placeholder="`${table.getState().pagination.pageSize}`"
            />
          </SelectTrigger>
          <SelectContent side="top">
            <SelectItem
              v-for="pageSize in [10, 20, 30, 40, 50]"
              :key="pageSize"
              :value="`${pageSize}`"
            >
              {{ pageSize }}
            </SelectItem>
          </SelectContent>
        </Select>
      </div>
      <div class="text-sm font-medium whitespace-nowrap tabular-nums">
        Page {{ table.getState().pagination.pageIndex + 1 }} of
        {{ Math.max(table.getPageCount(), 1) }}
      </div>
      <div class="flex items-center gap-1">
        <Button
          variant="outline"
          size="icon"
          class="hidden size-8 lg:flex"
          :disabled="!table.getCanPreviousPage()"
          @click="table.setPageIndex(0)"
        >
          <ChevronsLeft class="size-4" aria-hidden="true" />
          <span class="sr-only">First page</span>
        </Button>
        <Button
          variant="outline"
          size="icon"
          class="size-8"
          :disabled="!table.getCanPreviousPage()"
          @click="table.previousPage()"
        >
          <ChevronLeft class="size-4" aria-hidden="true" />
          <span class="sr-only">Previous page</span>
        </Button>
        <Button
          variant="outline"
          size="icon"
          class="size-8"
          :disabled="!table.getCanNextPage()"
          @click="table.nextPage()"
        >
          <ChevronRight class="size-4" aria-hidden="true" />
          <span class="sr-only">Next page</span>
        </Button>
        <Button
          variant="outline"
          size="icon"
          class="hidden size-8 lg:flex"
          :disabled="!table.getCanNextPage()"
          @click="table.setPageIndex(table.getPageCount() - 1)"
        >
          <ChevronsRight class="size-4" aria-hidden="true" />
          <span class="sr-only">Last page</span>
        </Button>
      </div>
    </div>
  </div>
</template>
