// packages/vue/components/gantt/GanttMilestone.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'
import type { GanttTask } from './types'

interface Props {
  task: GanttTask
  left: number
  top: number
  size?: number
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<Props>(), {
  size: 16,
})

const emits = defineEmits<{
  (e: 'click', task: GanttTask): void
}>()
</script>

<template>
  <div
    data-uipkge
    data-slot="gantt-milestone"
    :style="{
      left: `${left - size / 2}px`,
      top: `${top - size / 2}px`,
      width: `${size}px`,
      height: `${size}px`,
    }"
    :class="
      cn(
        'border-primary bg-primary absolute z-20 rotate-45 cursor-pointer rounded-xs border-2 shadow-sm transition-transform hover:scale-125',
        props.class,
      )
    "
    :title="`${task.name} (${task.startDate})`"
    @click="$emit('click', task)"
  />
</template>

// packages/react/components/gantt/GanttMilestone.tsx
'use client'

import * as React from 'react'
import { cn } from '@/lib/utils'
import type { GanttTask } from './types'

export interface GanttMilestoneProps extends React.HTMLAttributes<HTMLDivElement> {
  task: GanttTask
  left: number
  top: number
  size?: number
  onTaskClick?: (task: GanttTask) => void
}

export const GanttMilestone = React.forwardRef<HTMLDivElement, GanttMilestoneProps>(
  ({ className, task, left, top, size = 16, onTaskClick, ...props }, ref) => {
    return (
      <div
        ref={ref}
        data-uipkge=""
        data-slot="gantt-milestone"
        style={{
          left: `${left - size / 2}px`,
          top: `${top - size / 2}px`,
          width: `${size}px`,
          height: `${size}px`,
        }}
        title={`${task.name} (${task.startDate})`}
        className={cn(
          'border-primary bg-primary absolute z-20 rotate-45 cursor-pointer rounded-xs border-2 shadow-sm transition-transform hover:scale-125',
          className,
        )}
        onClick={() => onTaskClick?.(task)}
        {...props}
      />
    )
  },
)

GanttMilestone.displayName = 'GanttMilestone'
